[build]
target = "web/game.html"

[serve]
port = 8823
headers = { "Cross-Origin-Opener-Policy" = "same-origin", "Cross-Origin-Embedder-Policy" = "require-corp" }

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c",
    "mv \"$TRUNK_STAGING_DIR/index.html\" \"$TRUNK_STAGING_DIR/game.html\" && cp web/shell/index.html \"$TRUNK_STAGING_DIR/index.html\"",
]
