// Portal vortex (ported from nt-recreated-bevy `assets/shaders/vortex.wgsl`,
// itself a direct transcription of `scrDrawSpiral.gml`).
// Rendered as ONE fullscreen quad: each wisp is a transformed sample of the
// real spiral art; growth/alpha/lightning follow the GameMaker laws.
// Bevy-isms removed: no `#import`, no material bind-group macro. Uniforms
// arrive in one globals block; the seven art textures share one Linear
// sampler.
// `view` maps screen uv to wisp coord space: the live GUI view rect
// `(view_w/2, 120, view_w, 240)` — GML `display_set_gui_size(view)`
// makes GUI px == view px 1:1, so uv spans the GUI exactly and wisps
// drawn at GUI coords land 1:1 on screen, filling the corners like
// `draw_sprite_ext(view_xview + x, ...)` does.

struct VortexGlobals {
    wisps: array<vec4<f32>, 128>,
    debris: array<vec4<f32>, 32>,
    // Per-wisp bolt clock (lanim, langle radians), indexed like wisps.
    // vec4 (not vec2): uniform arrays need a 16-byte stride.
    streams: array<vec4<f32>, 128>,
    // Venuz star motes ([x, y, xscale, frame]; x < -100 parks the slot).
    stars: array<vec4<f32>, 128>,
    glob_a: vec4<f32>,
    glob_b: vec4<f32>,
    // Look center + visible extent in wisp coord space.
    view: vec4<f32>,
};

@group(0) @binding(0) var<uniform> g: VortexGlobals;
@group(1) @binding(0) var spiral_tex: texture_2d<f32>;
@group(1) @binding(1) var bolt_tex: texture_2d<f32>;
@group(1) @binding(2) var debris_tex: texture_2d<f32>;
@group(1) @binding(3) var spiral_proto_tex: texture_2d<f32>;
@group(1) @binding(4) var spiral_idpd_tex: texture_2d<f32>;
@group(1) @binding(5) var spiral_idpd2_tex: texture_2d<f32>;
@group(1) @binding(6) var star_tex: texture_2d<f32>;
@group(1) @binding(7) var lin_smp: sampler;

struct VsOut {
    @builtin(position) pos: vec4<f32>,
    // Screen uv, y-down (0,0) = top-left, like canvas space.
    @location(0) uv: vec2<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) i: u32) -> VsOut {
    let x = f32(i / 2u) * 4.0 - 1.0;
    let y = f32(i % 2u) * 4.0 - 1.0;
    var out: VsOut;
    out.pos = vec4<f32>(x, y, 0.0, 1.0);
    out.uv = vec2<f32>((x + 1.0) * 0.5, (1.0 - y) * 0.5);
    return out;
}

const N: u32 = 128u;
const BOLT_FRAMES: f32 = 6.0;

// Exact GML growth table 0..119 (xscale at tick age, before death at >2.5).
// Generated by iterating the GML recurrence. Lerp for fractional ages.
const SCALE_TABLE: array<f32, 120> = array<f32, 120>(
    0.000000, 0.000200, 0.000600, 0.001201, 0.002002, 0.003004, 0.004207, 0.005613,
    0.007221, 0.009033, 0.011050, 0.013272, 0.015700, 0.018337, 0.021183, 0.024239,
    0.027508, 0.030990, 0.034688, 0.038604, 0.042738, 0.047095, 0.051674, 0.056480,
    0.061514, 0.066779, 0.072278, 0.078013, 0.083987, 0.090204, 0.096665, 0.103376,
    0.110338, 0.117557, 0.125034, 0.132774, 0.140781, 0.149059, 0.157613, 0.166445,
    0.175562, 0.184967, 0.194666, 0.204663, 0.214963, 0.225572, 0.236495, 0.247737,
    0.259305, 0.271204, 0.283440, 0.296019, 0.308948, 0.322234, 0.335883, 0.349902,
    0.364299, 0.379081, 0.394254, 0.409828, 0.425810, 0.442209, 0.459032, 0.476288,
    0.493987, 0.512137, 0.530748, 0.549829, 0.569390, 0.589442, 0.609994, 0.631057,
    0.652643, 0.674762, 0.697426, 0.720646, 0.744435, 0.768805, 0.793769, 0.819340,
    0.845531, 0.872355, 0.899828, 0.927963, 0.956775, 0.986279, 1.016491, 1.047426,
    1.079101, 1.111533, 1.144739, 1.178736, 1.213543, 1.249177, 1.285658, 1.323006,
    1.361239, 1.400380, 1.440448, 1.481465, 1.523453, 1.566435, 1.610434, 1.655473,
    1.701577, 1.748772, 1.797082, 1.846534, 1.897155, 1.948972, 2.002015, 2.056312,
    2.111892, 2.168787, 2.227029, 2.286648, 2.347680, 2.410156, 2.474113, 2.539587
);

fn wisp_scale(age: f32) -> f32 {
    if (age <= 0.0) { return 0.0; }
    if (age >= 119.0) { return SCALE_TABLE[119]; }
    let i = u32(age);
    let f = fract(age);
    return mix(SCALE_TABLE[i], SCALE_TABLE[i + 1u], f);
}

// Proto growth (grow base 0.0005 from `random(0.01)` mean head-start 0.005).
// Same recurrence/baking as SCALE_TABLE, reaches 2.5 around tick 86.
const PROTO_TABLE: array<f32, 120> = array<f32, 120>(
    0.005500, 0.006503, 0.008009, 0.010019, 0.012534, 0.015555, 0.019084, 0.023123,
    0.027673, 0.032737, 0.038318, 0.044418, 0.051040, 0.058188, 0.065866, 0.074076,
    0.082824, 0.092113, 0.101949, 0.112337, 0.123281, 0.134788, 0.146862, 0.159512,
    0.172741, 0.186559, 0.200971, 0.215984, 0.231608, 0.247849, 0.264716, 0.282218,
    0.300363, 0.319161, 0.338622, 0.358755, 0.379571, 0.401081, 0.423296, 0.446227,
    0.469887, 0.494287, 0.519440, 0.545359, 0.572058, 0.599551, 0.627852, 0.656975,
    0.686937, 0.717752, 0.749438, 0.782010, 0.815485, 0.849883, 0.885219, 0.921514,
    0.958786, 0.997056, 1.036343, 1.076669, 1.118055, 1.160523, 1.204096, 1.248797,
    1.294650, 1.341681, 1.389914, 1.439375, 1.490092, 1.542091, 1.595402, 1.650052,
    1.706073, 1.763495, 1.822349, 1.882668, 1.944485, 2.007835, 2.072752, 2.139272,
    2.207434, 2.277274, 2.348832, 2.422149, 2.497266, 2.574225, 2.653071, 2.733847,
    2.816601, 2.901380, 2.988232, 3.077208, 3.168360, 3.261740, 3.357404, 3.455407,
    3.555807, 3.658663, 3.764036, 3.871990, 3.982589, 4.095900, 4.211991, 4.330932,
    4.452796, 4.577658, 4.705594, 4.836684, 4.971010, 5.108655, 5.249706, 5.394252,
    5.542384, 5.694199, 5.849793, 6.009267, 6.172725, 6.340273, 6.512023, 6.688088
);

fn proto_scale(age: f32) -> f32 {
    if (age <= 0.0) { return 0.0; }
    if (age >= 119.0) { return PROTO_TABLE[119]; }
    let i = u32(age);
    let f = fract(age);
    return mix(PROTO_TABLE[i], PROTO_TABLE[i + 1u], f);
}

// Per-wisp lightning clock comes from the sim (`Spiral` lanim/langle,
// advanced per tick in `SpiralCtl`); the slot matches the wisp slot.

@fragment
fn fs_main(in: VsOut) -> @location(0) vec4<f32> {
    let gui = vec2<f32>(
        g.view.x + (in.uv.x - 0.5) * g.view.z,
        g.view.y + (in.uv.y - 0.5) * g.view.w,
    );
    let tick_now = g.glob_a.x;
    let drain_bias = g.glob_a.y;
    let bg_alpha = g.glob_b.y;
    let thresh = g.glob_b.z;
    // SpiralKind discriminant + jungle-debris flag (see Rust glob docs).
    let kind = g.glob_b.w - floor(g.glob_b.w / 4.0) * 4.0;
    let debris_big = g.glob_b.w >= 4.0;
    var acc = vec3<f32>(g.glob_a.z, g.glob_a.w, g.glob_b.x);
    var out_alpha = bg_alpha;

    // Oldest drawn first, so the NEWEST wisp lands on top: GML `with`
    // iterates instances in creation order and script draws ignore depth.
    // Slot mapping matches CPU `(ticks-1) % N`.
    let base = u32(tick_now);
    for (var k: u32 = 0u; k < N; k = k + 1u) {
        let birth = base - (N - 1u - k);
        if (birth < 1u) { continue; }
        let slot = (birth - 1u) % N;
        let d = g.wisps[slot];
        if (d.z < 0.0) { continue; }
        let age = tick_now - d.z;
        if (age < 0.0) { continue; }
        let scale_age = age + drain_bias;
        var s = wisp_scale(scale_age);
        if (kind > 0.5 && kind < 1.5) {
            s = proto_scale(scale_age);
        }
        // Sim bolt clock for this wisp's own stream (GML Spiral
        // lanim/langle, NOT a birth-hash mean).
        let stream = g.streams[slot];
        let lanim = stream.x;
        if (s > thresh && !(lanim > 0.0 && lanim < 6.0)) { continue; }

        // IDPD2 variant rides in the rot sign (CPU); art is 128px single.
        let idpd2 = d.w < 0.0;
        let rot = abs(d.w);
        let c = cos(rot);
        let sn = sin(rot);
        var rel = gui - d.xy;
        rel = vec2<f32>(c * rel.x + sn * rel.y, -sn * rel.x + c * rel.y);

        // Lightning pass FIRST (scrDrawSpiral draws the bolt before the
        // wisp's own white/black spiral passes cover it).
        if (s > 0.05) {
            if (lanim > 0.0 && lanim < 6.0) {
                let frame = clamp(floor(lanim), 0.0, BOLT_FRAMES - 1.0);
                let langle = stream.y;
                // Bolt rotation is image_angle + langle with NO +45 (the
                // +45 in `rot` is wisp-art only): strip it back out here.
                let lc = cos(rot - 0.7853982 + langle);
                let ls = sin(rot - 0.7853982 + langle);
                var lrel = gui - d.xy;
                lrel = vec2<f32>(lc * lrel.x + ls * lrel.y, -ls * lrel.x + lc * lrel.y);
                // GML origin (180, 88): the bolt art's ink sits LEFT of
                // the draw point (opaque x 19..89 of the 176px cell, i.e.
                // ~-92 GUI px), so recenter by the origin, not the cell
                // half-extent.
                let lbolt_half = vec2<f32>(88.0, 88.0) * s;
                let buv = (lrel + vec2<f32>(92.0, 0.0) * s) / (lbolt_half * 2.0) + vec2<f32>(0.5, 0.5);
                if (all(buv > vec2<f32>(0.0)) & all(buv < vec2<f32>(1.0))) {
                    let bolt_uv_x = (frame * 176.0 + 0.5 + buv.x * 175.0) / 1056.0;
                    let bolt_uv_y = (0.5 + buv.y * 175.0) / 176.0;
                    let btex = textureSample(bolt_tex, lin_smp, vec2<f32>(bolt_uv_x, bolt_uv_y));
                    // GML: white 1 then black 0.4 - s/2
                    acc = mix(acc, btex.rgb, btex.a);
                    out_alpha = max(out_alpha, btex.a);
                    let bolt_black = clamp(0.4 - s * 0.5, 0.0, 1.0);
                    if (bolt_black > 0.001) {
                        acc = mix(acc, vec3<f32>(0.0), btex.a * bolt_black);
                    }
                }
            }
        }

        if (kind > 1.5 && kind < 2.5) {
            // IDPD: single 128x128 frame, origin centre.
            let half_ext = 64.0 * s * 10.0;
            let suv = rel / half_ext * 0.5 + vec2<f32>(0.5, 0.5);
            if (all(suv > vec2<f32>(0.0)) & all(suv < vec2<f32>(1.0))) {
                let uv = (suv * 127.0 + 0.5) / 128.0;
                var tex = textureSample(spiral_idpd_tex, lin_smp, uv);
                if (idpd2) {
                    tex = textureSample(spiral_idpd2_tex, lin_smp, uv);
                }
                acc = mix(acc, tex.rgb, tex.a);
                out_alpha = max(out_alpha, tex.a);
                let black_a = clamp(0.8 - s, 0.0, 1.0);
                if (black_a > 0.001) {
                    acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
                }
            }
            continue;
        }

        let suv = rel / (32.0 * s * 10.0) * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(suv > vec2<f32>(0.0)) & all(suv < vec2<f32>(1.0))) {
        // GML `Spiral/Create_0`: `image_speed = 2` on the 2-frame
        // `sprSpiral` strip advances the float index 2/step, so the
        // wrapped frame alternates 0, 1, 0, 1... (NOT pinned to 0:
        // even steps show the square-hole frame 0, odd steps the
        // round-hole frame 1 — the shimmering GML vortex core).
        let sframe = f32(u32(tick_now) % 2u);
            // Half-texel inset to avoid atlas bleeding (sprite is 64x64 in 128x64 strip)
            let uv_x = (sframe * 64.0 + 0.5 + suv.x * 63.0) / 128.0;
            let uv_y = (0.5 + suv.y * 63.0) / 64.0;
            var tex = textureSample(spiral_tex, lin_smp, vec2<f32>(uv_x, uv_y));
            if (kind > 0.5 && kind < 1.5) {
                tex = textureSample(spiral_proto_tex, lin_smp, vec2<f32>(uv_x, uv_y));
            }
            // GML two-pass: white (c_white, alpha tex.a) then black 0.8 - s
            acc = mix(acc, tex.rgb, tex.a);
            out_alpha = max(out_alpha, tex.a);
            let black_a = clamp(0.8 - s, 0.0, 1.0);
            if (black_a > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
            }
        }
    }

    // SpiralDebris pass - drawn AFTER all wisps (scrDrawSpiral order), on top.
    // CPU supplies [x, y, rot_rad, frame + xscale/32]; x < -100 = empty slot.
    // Jungle debris (sprDebris105) uses 16px frames instead of 8px.
    for (var i: u32 = 0u; i < 32u; i = i + 1u) {
        let d = g.debris[i];
        if (d.x < -100.0) { continue; }
        // Jungle debris uses 16px frames, all other areas 8px.
        var fpx = 8.0;
        if (debris_big) {
            fpx = 16.0;
        }
        let xs = fract(d.w) * 32.0;
        let frame = floor(d.w);
        let half_ext = (fpx * 0.5) * xs;
        var rel = gui - d.xy;
        let c = cos(d.z);
        let sn = sin(d.z);
        rel = vec2<f32>(c * rel.x + sn * rel.y, -sn * rel.x + c * rel.y);
        let duv = rel / half_ext * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(duv > vec2<f32>(0.0)) & all(duv < vec2<f32>(1.0))) {
            // frames in a 4-wide horizontal strip, half-texel inset
            let uv_x = (frame * fpx + 0.5 + duv.x * (fpx - 1.0)) / (4.0 * fpx);
            let uv_y = (0.5 + duv.y * (fpx - 1.0)) / fpx;
            let tex = textureSample(debris_tex, lin_smp, vec2<f32>(uv_x, uv_y));
            // scrDrawSpiral: white 1, then black (1 - xscale)
            acc = mix(acc, tex.rgb, tex.a);
            out_alpha = max(out_alpha, tex.a);
            let black_a = clamp(1.0 - xs, 0.0, 1.0);
            if (black_a > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
            }
        }
    }
    // SpiralStar pass - drawn AFTER debris (GML `with` order), on top.
    // CPU supplies [x, y, xscale, frame]; x < -100 = empty slot.
    // sprSpiralStar is a 2-frame 3x3 strip (frame 0/1, origin centre).
    for (var si: u32 = 0u; si < 128u; si = si + 1u) {
        let st = g.stars[si];
        if (st.x < -100.0) { continue; }
        let xs = st.z;
        if (xs <= 0.001) { continue; }
        var srel = gui - st.xy;
        // GML draws stars unrotated (image_angle stays 0: the Step
        // never turns it), scaled by xscale on both axes.
        let sduv = srel / (1.5 * xs) * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(sduv > vec2<f32>(0.0)) & all(sduv < vec2<f32>(1.0))) {
            // two 3px frames side by side in the 6x3 strip
            let suv_x = (st.w * 3.0 + 0.5 + sduv.x * 2.0) / 6.0;
            let suv_y = (0.5 + sduv.y * 2.0) / 3.0;
            let stex = textureSample(star_tex, lin_smp, vec2<f32>(suv_x, suv_y));
            // scrDrawSpiral: white 1, then black (1 - xscale)
            acc = mix(acc, stex.rgb, stex.a);
            out_alpha = max(out_alpha, stex.a);
            let sblack = clamp(1.0 - xs, 0.0, 1.0);
            if (sblack > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), stex.a * sblack);
            }
        }
    }
    return vec4<f32>(acc, out_alpha);
}
