use super::data::EnemyKind;

#[derive(Clone, Copy)]
#[allow(dead_code)]
pub struct EnemyDef {
    pub name: &'static str,
    pub hp: i32,
    pub speed: f32,
    pub accel: f32,
    pub radius: f32,
    pub size: f32,
    pub color: [f32; 4],
    pub sprite: &'static str,
    pub score: u32,
    pub touch_damage: i32,
    pub rad_drop: usize,
    pub drop_chance: usize,
    pub weapon_chance: usize,
    pub preferred_range: f32,
    pub shoot_range: f32,
    pub attack_cooldown: f32,
    pub bullets_per_shot: usize,
    pub burst: bool,
    pub burst_interval: f32,
    pub fan_spread: f32,
    pub projectile_speed: f32,
    pub projectile_spread: f32,
    pub projectile_damage: i32,
    pub projectile_radius: f32,
    pub projectile_lifetime: f32,
    pub projectile_color: [f32; 4],
    pub projectile_size: f32,
    pub boss: bool,
}

pub fn enemy_def(kind: EnemyKind) -> EnemyDef {
    match kind {
        EnemyKind::Maggot => EnemyDef {
            name: "Maggot",
            hp: 2,
            speed: 75.0,
            accel: 1800.0,
            radius: 9.0,
            size: 17.0,
            color: [0.95, 0.55, 0.25, 1.0],
            sprite: "images/sprMaggotIdle.png",
            score: 5,
            touch_damage: 1,
            rad_drop: 1,
            drop_chance: 0,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Bandit => EnemyDef {
            name: "Bandit",
            hp: 4,
            speed: 24.0,
            accel: 800.0,
            radius: 12.0,
            size: 24.0,
            color: [0.85, 0.22, 0.18, 1.0],
            sprite: "images/sprBanditIdle.png",
            score: 10,
            touch_damage: 0,
            rad_drop: 2,
            drop_chance: 16,
            weapon_chance: 0,
            preferred_range: 90.0,
            shoot_range: 480.0,
            attack_cooldown: 1.65,
            bullets_per_shot: 1,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 120.0,
            projectile_spread: 0.175,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 3.5,
            projectile_color: [1.0, 0.35, 0.08, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::Scorpion => EnemyDef {
            name: "Scorpion",
            hp: 16,
            speed: 24.0,
            accel: 800.0,
            radius: 14.0,
            size: 28.0,
            color: [0.35, 0.85, 0.28, 1.0],
            sprite: "images/sprScorpionIdle.png",
            score: 18,
            touch_damage: 5,
            rad_drop: 10,
            drop_chance: 15,
            weapon_chance: 0,
            preferred_range: 120.0,
            shoot_range: 210.0,
            attack_cooldown: 0.75,
            bullets_per_shot: 10,
            burst: true,
            burst_interval: 0.066,
            fan_spread: 0.0,
            projectile_speed: 105.0,

            projectile_spread: 0.349,
            projectile_damage: 2,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [0.35, 1.0, 0.25, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::Assassin => EnemyDef {
            name: "Assassin",
            hp: 7,
            speed: 84.0,
            accel: 880.0,
            radius: 11.0,
            size: 22.0,
            color: [0.2, 0.18, 0.24, 1.0],
            sprite: "images/sprJungleAssassinIdle.png",
            score: 25,
            touch_damage: 0,
            rad_drop: 8,
            drop_chance: 16,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Freak => EnemyDef {
            name: "Freak",
            hp: 7,
            speed: 112.0,
            accel: 5400.0,
            radius: 13.0,
            size: 26.0,
            color: [0.6, 0.35, 0.85, 1.0],
            sprite: "images/sprFreak1Idle.png",
            score: 15,
            touch_damage: 3,
            rad_drop: 1,
            drop_chance: 10,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::BigBandit => EnemyDef {
            name: "Big Bandit",
            hp: 100,
            speed: 80.0,
            accel: 1000.0,
            radius: 26.0,
            size: 52.0,
            color: [0.95, 0.25, 0.12, 1.0],
            sprite: "images/sprBanditBossIdle.png",
            score: 500,
            touch_damage: 0,
            rad_drop: 30,
            drop_chance: 200,
            weapon_chance: 0,
            preferred_range: 170.0,
            shoot_range: 560.0,
            attack_cooldown: 1.15,
            bullets_per_shot: 5,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.16,
            projectile_speed: 240.0,
            projectile_spread: 0.06,
            projectile_damage: 3,
            projectile_radius: 4.5,
            projectile_lifetime: 3.2,
            projectile_color: [1.0, 0.28, 0.08, 1.0],
            projectile_size: 8.0,
            boss: true,
        },
        EnemyKind::BigBanditLoop => EnemyDef {
            name: "Loop Big Bandit",
            hp: 130,
            speed: 95.0,
            accel: 1200.0,
            radius: 28.0,
            size: 56.0,
            color: [1.0, 0.42, 0.18, 1.0],
            sprite: enemy_def(EnemyKind::BigBandit).sprite,
            score: 850,
            touch_damage: 7,
            rad_drop: 35,
            drop_chance: 70,
            weapon_chance: 12,
            preferred_range: 190.0,
            shoot_range: 620.0,
            attack_cooldown: 0.95,
            bullets_per_shot: 7,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.14,
            projectile_speed: 215.0,
            projectile_spread: 0.05,
            projectile_damage: 4,
            projectile_radius: 4.5,
            projectile_lifetime: 3.2,
            projectile_color: [1.0, 0.45, 0.12, 1.0],
            projectile_size: 8.5,
            boss: true,
        },
        EnemyKind::Throne => EnemyDef {
            name: "The Throne",
            hp: 1500,
            speed: 0.0,
            accel: 650.0,
            radius: 44.0,
            size: 88.0,
            color: [1.0, 0.78, 0.25, 1.0],
            sprite: "images/sprNothingMiddle.png",
            score: 5000,
            touch_damage: 10,
            rad_drop: 500,
            drop_chance: 100,
            weapon_chance: 25,
            preferred_range: 0.0,
            shoot_range: 999.0,
            attack_cooldown: 0.7,
            bullets_per_shot: 7,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.1,
            projectile_speed: 210.0,
            projectile_spread: 0.0,
            projectile_damage: 3,
            projectile_radius: 5.5,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.75, 0.25, 1.0],
            projectile_size: 9.0,
            boss: true,
        },
        EnemyKind::ThroneII => EnemyDef {
            name: "Throne II",
            hp: 600,
            speed: 90.0,
            accel: 900.0,
            radius: 30.0,
            size: 60.0,
            color: [0.45, 1.0, 0.55, 1.0],
            sprite: "images/sprNothing2Idle.png",
            score: 8000,
            touch_damage: 10,
            rad_drop: 70,
            drop_chance: 100,
            weapon_chance: 25,
            preferred_range: 0.0,
            shoot_range: 999.0,
            attack_cooldown: 0.85,
            bullets_per_shot: 3,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 180.0,
            projectile_spread: 0.0,
            projectile_damage: 5,
            projectile_radius: 8.0,
            projectile_lifetime: 1.4,
            projectile_color: [0.35, 1.0, 0.45, 1.0],
            projectile_size: 14.0,
            boss: true,
        },
        EnemyKind::Hyper => EnemyDef {
            name: "Hyper Crystal",
            hp: 550,
            speed: 35.0,
            accel: 500.0,
            radius: 34.0,
            size: 68.0,
            color: [1.0, 0.25, 0.35, 1.0],
            sprite: "images/sprHyperCrystalIdle.png",
            score: 9000,
            touch_damage: 200,
            rad_drop: 150,
            drop_chance: 100,
            weapon_chance: 20,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 1.1,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 0.0,
            boss: true,
        },
        EnemyKind::Rat => EnemyDef {
            name: "Rat",
            hp: 7,
            speed: 110.0,
            accel: 6000.0,
            radius: 8.0,
            size: 14.0,
            color: [0.75, 0.6, 0.45, 1.0],
            sprite: "images/sprRatIdle.png",
            score: 5,
            touch_damage: 2,
            rad_drop: 4,
            drop_chance: 0,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::BigRat => EnemyDef {
            name: "Big Rat",
            hp: 35,
            speed: 95.0,
            accel: 4800.0,
            radius: 13.0,
            size: 26.0,
            color: [0.65, 0.5, 0.35, 1.0],
            sprite: "images/sprRatkingIdle.png",
            score: 15,
            touch_damage: 0,
            rad_drop: 20,
            drop_chance: 8,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::RobotGuard => EnemyDef {
            name: "Robot Guard",
            hp: 15,
            speed: 30.0,
            accel: 900.0,
            radius: 11.0,
            size: 22.0,
            color: [0.55, 0.62, 0.7, 1.0],
            sprite: "images/sprSnowBotIdle.png",
            score: 20,
            touch_damage: 0,
            rad_drop: 5,
            drop_chance: 16,
            weapon_chance: 0,
            preferred_range: 180.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.8, 0.3, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::Turret => EnemyDef {
            name: "Turret",
            hp: 40,
            speed: 0.0,
            accel: 0.0,
            radius: 12.0,
            size: 24.0,
            color: [0.45, 0.5, 0.55, 1.0],
            sprite: "images/sprTurretIdle.png",
            score: 15,
            touch_damage: 0,
            rad_drop: 1,
            drop_chance: 10,
            weapon_chance: 0,
            preferred_range: 999.0,
            shoot_range: 160.0,
            attack_cooldown: 1.83,
            bullets_per_shot: 10,
            burst: true,
            burst_interval: 0.1,
            fan_spread: 0.0,

            projectile_speed: 240.0,
            projectile_spread: 0.07,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.45, 0.2, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::SnowBandit => EnemyDef {
            name: "Snow Bandit",
            hp: 4,
            speed: 26.0,
            accel: 850.0,
            radius: 12.0,
            size: 24.0,
            color: [0.75, 0.85, 0.95, 1.0],
            sprite: "images/sprSnowBanditIdle.png",
            score: 20,
            touch_damage: 0,
            rad_drop: 2,
            drop_chance: 16,
            weapon_chance: 0,
            preferred_range: 110.0,
            shoot_range: 500.0,
            attack_cooldown: 1.5,
            bullets_per_shot: 1,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 130.0,
            projectile_spread: 0.175,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 3.5,
            projectile_color: [0.7, 0.9, 1.0, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::Wolf => EnemyDef {
            name: "Wolf",
            hp: 16,
            speed: 135.0,
            accel: 6000.0,
            radius: 10.0,
            size: 20.0,
            color: [0.85, 0.85, 0.9, 1.0],
            sprite: "images/sprWolfIdle.png",
            score: 18,
            touch_damage: 3,
            rad_drop: 6,
            drop_chance: 8,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::BigDog => EnemyDef {
            name: "Big Dog",
            hp: 300,
            speed: 40.0,
            accel: 700.0,
            radius: 36.0,
            size: 72.0,
            color: [0.65, 0.65, 0.7, 1.0],
            sprite: "images/sprScrapBossIdle.png",
            score: 1200,
            touch_damage: 0,
            rad_drop: 90,
            drop_chance: 80,
            weapon_chance: 15,
            preferred_range: 240.0,
            shoot_range: 999.0,
            attack_cooldown: 0.8,
            bullets_per_shot: 5,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.12,
            projectile_speed: 190.0,
            projectile_spread: 0.03,
            projectile_damage: 3,
            projectile_radius: 6.0,
            projectile_lifetime: 2.6,
            projectile_color: [1.0, 0.42, 0.12, 1.0],
            projectile_size: 9.0,
            boss: true,
        },
        EnemyKind::BigDogLoop => EnemyDef {
            name: "Loop Big Dog",
            hp: 260,
            speed: 55.0,
            accel: 850.0,
            radius: 38.0,
            size: 76.0,
            color: [0.85, 0.72, 0.65, 1.0],
            sprite: enemy_def(EnemyKind::BigDog).sprite,
            score: 1800,
            touch_damage: 8,
            rad_drop: 65,
            drop_chance: 90,
            weapon_chance: 20,
            preferred_range: 260.0,
            shoot_range: 999.0,
            attack_cooldown: 0.65,
            bullets_per_shot: 7,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.10,
            projectile_speed: 230.0,
            projectile_spread: 0.03,
            projectile_damage: 4,
            projectile_radius: 6.0,
            projectile_lifetime: 2.8,
            projectile_color: [1.0, 0.52, 0.16, 1.0],
            projectile_size: 9.5,
            boss: true,
        },
        EnemyKind::LilHunter => EnemyDef {
            name: "Lil Hunter",
            hp: 140,
            speed: 130.0,
            accel: 1100.0,
            radius: 20.0,
            size: 40.0,
            color: [0.55, 0.85, 1.0, 1.0],
            sprite: "images/sprLilHunter.png",
            score: 1500,
            touch_damage: 0,
            rad_drop: 20,
            drop_chance: 85,
            weapon_chance: 20,
            preferred_range: 190.0,
            shoot_range: 640.0,
            attack_cooldown: 0.55,
            bullets_per_shot: 2,
            burst: true,
            burst_interval: 0.12,
            fan_spread: 0.0,
            projectile_speed: 245.0,
            projectile_spread: 0.04,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 2.3,
            projectile_color: [0.6, 0.95, 1.0, 1.0],
            projectile_size: 7.0,
            boss: true,
        },
        EnemyKind::LilHunterLoop => EnemyDef {
            name: "Loop Lil Hunter",
            hp: 210,
            speed: 155.0,
            accel: 1300.0,
            radius: 21.0,
            size: 42.0,
            color: [0.75, 1.0, 1.0, 1.0],
            sprite: enemy_def(EnemyKind::LilHunter).sprite,
            score: 2200,
            touch_damage: 7,
            rad_drop: 60,
            drop_chance: 95,
            weapon_chance: 25,
            preferred_range: 210.0,
            shoot_range: 720.0,
            attack_cooldown: 0.42,
            bullets_per_shot: 5,
            burst: true,
            burst_interval: 0.055,
            fan_spread: 0.11,
            projectile_speed: 310.0,
            projectile_spread: 0.03,
            projectile_damage: 4,
            projectile_radius: 4.5,
            projectile_lifetime: 2.5,
            projectile_color: [0.75, 1.0, 1.0, 1.0],
            projectile_size: 7.5,
            boss: true,
        },
        EnemyKind::IdpdGrunt => EnemyDef {
            name: "IDPD Grunt",
            hp: 8,
            speed: 120.0,
            accel: 1100.0,
            radius: 13.0,
            size: 24.0,
            color: [0.25, 0.45, 0.95, 1.0],
            sprite: "images/sprGruntIdle.png",
            score: 18,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 18,
            weapon_chance: 4,
            preferred_range: 220.0,
            shoot_range: 520.0,
            attack_cooldown: 0.13,
            bullets_per_shot: 1,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 240.0,
            projectile_spread: 0.05,
            projectile_damage: 2,
            projectile_radius: 3.5,
            projectile_lifetime: 2.2,
            projectile_color: [0.45, 0.75, 1.0, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::IdpdShield => EnemyDef {
            name: "IDPD Shield",
            hp: 50,
            speed: 95.0,
            accel: 950.0,
            radius: 15.0,
            size: 28.0,
            color: [0.2, 0.5, 0.9, 1.0],
            sprite: "images/sprShielderIdle.png",
            score: 28,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 20,
            weapon_chance: 5,
            preferred_range: 180.0,
            shoot_range: 250.0,
            attack_cooldown: 1.66,
            bullets_per_shot: 8,
            burst: true,
            burst_interval: 0.1,
            fan_spread: 0.05,
            projectile_speed: 240.0,
            projectile_spread: 0.02,
            projectile_damage: 2,
            projectile_radius: 4.0,
            projectile_lifetime: 2.0,
            projectile_color: [0.4, 0.75, 1.0, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::IdpdElite => EnemyDef {
            name: "IDPD Elite",
            hp: 40,
            speed: 135.0,
            accel: 1200.0,
            radius: 14.0,
            size: 26.0,
            color: [0.4, 0.25, 1.0, 1.0],
            sprite: "images/sprEliteGruntIdle.png",
            score: 45,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 26,
            weapon_chance: 8,
            preferred_range: 260.0,
            shoot_range: 700.0,
            attack_cooldown: 0.6,
            bullets_per_shot: 5,
            burst: true,
            burst_interval: 0.05,
            fan_spread: 0.11,
            projectile_speed: 340.0,
            projectile_spread: 0.03,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 2.6,
            projectile_color: [0.55, 0.75, 1.0, 1.0],
            projectile_size: 7.5,
            boss: false,
        },
        EnemyKind::IdpdVan => EnemyDef {
            name: "IDPD Van",
            hp: 250,
            speed: 0.0,
            accel: 0.0,
            radius: 24.0,
            size: 44.0,
            color: [0.18, 0.28, 0.72, 1.0],
            sprite: "images/sprVanDrive.png",
            score: 80,
            touch_damage: 20,
            rad_drop: 0,
            drop_chance: 40,
            weapon_chance: 12,
            preferred_range: 0.0,
            shoot_range: 999.0,
            attack_cooldown: 2.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [0.4, 0.7, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Mom => EnemyDef {
            name: "Mom",
            hp: 280,
            speed: 40.0,
            accel: 700.0,
            radius: 28.0,
            size: 56.0,
            color: [0.55, 0.85, 0.35, 1.0],
            sprite: "images/sprMomIdle.png",
            score: 1200,
            touch_damage: 4,
            rad_drop: 50,
            drop_chance: 100,
            weapon_chance: 18,
            preferred_range: 160.0,
            shoot_range: 520.0,
            attack_cooldown: 1.1,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [0.45, 1.0, 0.35, 1.0],
            projectile_size: 10.0,
            boss: true,
        },
        EnemyKind::FrogQueen => EnemyDef {
            name: "Frog Queen",
            hp: 490,
            speed: 55.0,
            accel: 800.0,
            radius: 26.0,
            size: 52.0,
            color: [0.45, 0.9, 0.4, 1.0],
            sprite: "images/sprFrogQueenIdle.png",
            score: 2000,
            touch_damage: 10,
            rad_drop: 30,
            drop_chance: 200,
            weapon_chance: 0,

            preferred_range: 140.0,
            shoot_range: 999.0,
            attack_cooldown: 1.3,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 120.0,
            projectile_spread: 0.13,
            projectile_damage: 4,
            projectile_radius: 6.0,
            projectile_lifetime: 3.0,
            projectile_color: [0.5, 1.0, 0.4, 1.0],
            projectile_size: 11.0,
            boss: true,
        },
        EnemyKind::Technomancer => EnemyDef {
            name: "Technomancer",
            hp: 350,
            speed: 0.0,
            accel: 0.0,
            radius: 22.0,
            size: 44.0,
            color: [0.55, 0.35, 0.85, 1.0],

            sprite: "images/sprTechnoMancer.png",
            score: 1500,
            touch_damage: 0,
            rad_drop: 50,
            drop_chance: 100,
            weapon_chance: 15,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 2.2,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: true,
        },
        EnemyKind::Captain => EnemyDef {
            name: "Captain",
            hp: 420,
            speed: 110.0,
            accel: 1400.0,
            radius: 16.0,
            size: 32.0,
            color: [0.35, 0.55, 0.95, 1.0],
            sprite: "images/sprPopoCaptainIdle.png",
            score: 4000,
            touch_damage: 6,
            rad_drop: 80,
            drop_chance: 100,
            weapon_chance: 20,
            preferred_range: 140.0,
            shoot_range: 700.0,
            attack_cooldown: 0.75,
            bullets_per_shot: 5,
            burst: true,
            burst_interval: 0.06,
            fan_spread: 0.12,
            projectile_speed: 240.0,
            projectile_spread: 0.04,
            projectile_damage: 4,
            projectile_radius: 4.5,
            projectile_lifetime: 2.8,
            projectile_color: [0.45, 0.75, 1.0, 1.0],
            projectile_size: 8.0,
            boss: true,
        },
        EnemyKind::Ballguy => EnemyDef {
            name: "Ballguy",
            hp: 5,
            speed: 95.0,
            accel: 4200.0,
            radius: 11.0,
            size: 20.0,
            color: [0.45, 0.9, 0.4, 1.0],

            sprite: "images/sprExploderIdle.png",
            score: 12,
            touch_damage: 0,
            rad_drop: 5,
            drop_chance: 20,
            weapon_chance: 2,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 1.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::FrogEgg => EnemyDef {
            name: "Frog Egg",
            hp: 35,
            speed: 0.0,
            accel: 0.0,
            radius: 10.0,
            size: 18.0,
            color: [0.7, 0.85, 0.35, 1.0],
            sprite: "images/sprFrogEgg.png",
            score: 5,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 50,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 4.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Necromancer => EnemyDef {
            name: "Necromancer",
            hp: 6,
            speed: 28.0,
            accel: 700.0,
            radius: 12.0,
            size: 24.0,
            color: [0.65, 0.35, 0.8, 1.0],
            sprite: "images/sprNecromancerIdle.png",
            score: 30,
            touch_damage: 0,
            rad_drop: 8,
            drop_chance: 35,
            weapon_chance: 5,
            preferred_range: 180.0,
            shoot_range: 0.0,
            attack_cooldown: 0.75,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Spider => EnemyDef {
            name: "Spider",
            hp: 18,
            speed: 130.0,
            accel: 5000.0,
            radius: 10.0,
            size: 20.0,
            color: [0.55, 0.2, 0.65, 1.0],
            sprite: "images/sprSpiderIdle.png",
            score: 14,
            touch_damage: 3,
            rad_drop: 9,
            drop_chance: 18,
            weapon_chance: 2,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Crystal => EnemyDef {
            name: "Crystal",
            hp: 2,
            speed: 0.0,
            accel: 0.0,
            radius: 12.0,
            size: 24.0,
            color: [0.85, 0.45, 1.0, 1.0],

            sprite: "images/sprCrystalProp.png",
            score: 16,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 0,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 160.0,
            projectile_spread: 0.05,
            projectile_damage: 0,
            projectile_radius: 4.0,
            projectile_lifetime: 2.5,
            projectile_color: [0.9, 0.5, 1.0, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::LaserCrystal => EnemyDef {
            name: "Laser Crystal",
            hp: 45,
            speed: 0.0,
            accel: 0.0,
            radius: 14.0,
            size: 28.0,
            color: [1.0, 0.25, 0.45, 1.0],
            sprite: "images/sprLaserCrystalIdle.png",
            score: 28,
            touch_damage: 20,
            rad_drop: 22,
            drop_chance: 30,
            weapon_chance: 5,
            preferred_range: 0.0,
            shoot_range: 160.0,
            attack_cooldown: 3.17,
            bullets_per_shot: 4,
            burst: true,
            burst_interval: 0.167,
            fan_spread: 0.0,
            projectile_speed: 320.0,
            projectile_spread: 0.0,
            projectile_damage: 4,
            projectile_radius: 3.5,
            projectile_lifetime: 1.2,
            projectile_color: [1.0, 0.2, 0.35, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::Sniper => EnemyDef {
            name: "Sniper",
            hp: 6,
            speed: 40.0,
            accel: 900.0,
            radius: 11.0,
            size: 22.0,
            color: [0.4, 0.55, 0.75, 1.0],
            sprite: "images/sprSniperIdle.png",
            score: 22,
            touch_damage: 0,
            rad_drop: 8,
            drop_chance: 22,
            weapon_chance: 4,
            preferred_range: 220.0,
            shoot_range: 800.0,
            attack_cooldown: 1.42,

            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.07,
            projectile_speed: 480.0,
            projectile_spread: 0.01,
            projectile_damage: 3,
            projectile_radius: 3.5,
            projectile_lifetime: 2.0,
            projectile_color: [0.6, 0.85, 1.0, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::Crab => EnemyDef {
            name: "Crab",
            hp: 12,
            speed: 70.0,
            accel: 2200.0,
            radius: 12.0,
            size: 22.0,
            color: [0.95, 0.45, 0.25, 1.0],
            sprite: "images/sprCrabIdle.png",
            score: 12,
            touch_damage: 3,
            rad_drop: 3,
            drop_chance: 30,
            weapon_chance: 0,

            preferred_range: 90.0,
            shoot_range: 999.0,
            attack_cooldown: 1.5,
            bullets_per_shot: 16,
            burst: true,
            burst_interval: 0.033,
            fan_spread: 0.35,
            projectile_speed: 180.0,
            projectile_spread: 0.052,
            projectile_damage: 2,
            projectile_radius: 3.5,
            projectile_lifetime: 2.5,
            projectile_color: [1.0, 0.6, 0.3, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::OldGuardian => EnemyDef {
            name: "Old Guardian",
            hp: 180,
            speed: 55.0,
            accel: 900.0,
            radius: 22.0,
            size: 44.0,
            color: [0.75, 0.7, 0.55, 1.0],
            sprite: "images/sprOldGuardianIdle.png",
            score: 2000,
            touch_damage: 5,
            rad_drop: 40,
            drop_chance: 100,
            weapon_chance: 15,
            preferred_range: 120.0,
            shoot_range: 500.0,
            attack_cooldown: 1.0,
            bullets_per_shot: 4,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.14,
            projectile_speed: 180.0,
            projectile_spread: 0.05,
            projectile_damage: 3,
            projectile_radius: 4.5,
            projectile_lifetime: 2.5,
            projectile_color: [0.9, 0.85, 0.5, 1.0],
            projectile_size: 8.0,
            boss: true,
        },
        EnemyKind::PalaceGuardian => EnemyDef {
            name: "Palace Guardian",
            hp: 45,
            speed: 95.0,
            accel: 2800.0,
            radius: 14.0,
            size: 28.0,
            color: [0.85, 0.75, 0.45, 1.0],
            sprite: "images/sprGuardianIdle.png",
            score: 40,
            touch_damage: 4,
            rad_drop: 10,
            drop_chance: 40,
            weapon_chance: 6,
            preferred_range: 80.0,
            shoot_range: 420.0,
            attack_cooldown: 0.9,

            bullets_per_shot: 3,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.7,
            projectile_speed: 60.0,
            projectile_spread: 0.04,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 2.2,
            projectile_color: [1.0, 0.85, 0.4, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::Mimic => EnemyDef {
            name: "Mimic",
            hp: 4,
            speed: 60.0,
            accel: 2000.0,
            radius: 12.0,
            size: 24.0,
            color: [0.7, 0.4, 0.7, 1.0],
            sprite: "images/sprMimicIdle.png",
            score: 25,
            touch_damage: 3,
            rad_drop: 6,
            drop_chance: 20,
            weapon_chance: 5,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 4.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::SuperMimic => EnemyDef {
            name: "Super Mimic",
            hp: 15,
            speed: 65.0,
            accel: 2200.0,
            radius: 14.0,
            size: 28.0,
            color: [0.8, 0.3, 0.5, 1.0],
            sprite: "images/sprSuperMimicIdle.png",
            score: 60,
            touch_damage: 4,
            rad_drop: 15,
            drop_chance: 30,
            weapon_chance: 10,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 6.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::WepMimic => EnemyDef {
            name: "Weapon Mimic",
            hp: 15,
            speed: 65.0,
            accel: 2200.0,
            radius: 14.0,
            size: 28.0,
            color: [0.6, 0.6, 0.8, 1.0],
            sprite: "images/sprWepMimicIdle.png",
            score: 60,
            touch_damage: 4,
            rad_drop: 15,
            drop_chance: 200,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 4.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::YvBoss => EnemyDef {
            name: "Y.V. Boss",
            hp: 700,
            speed: 30.0,
            accel: 900.0,
            radius: 20.0,
            size: 40.0,
            color: [0.85, 0.75, 0.2, 1.0],
            sprite: "images/sprYVBossIdle.png",
            score: 500,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 100,
            weapon_chance: 10,
            preferred_range: 200.0,
            shoot_range: 600.0,
            attack_cooldown: 1.2,
            bullets_per_shot: 5,
            burst: true,
            burst_interval: 0.08,
            fan_spread: 0.15,
            projectile_speed: 240.0,
            projectile_spread: 0.05,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.85, 0.2, 1.0],
            projectile_size: 8.0,
            boss: true,
        },
        EnemyKind::CrownGuardian => EnemyDef {
            name: "Crown Guardian",
            hp: 70,
            speed: 60.0,
            accel: 1200.0,
            radius: 14.0,
            size: 28.0,
            color: [0.9, 0.8, 0.3, 1.0],
            sprite: "images/sprCrownGuardianIdle.png",
            score: 120,
            touch_damage: 0,
            rad_drop: 11,
            drop_chance: 40,
            weapon_chance: 6,
            preferred_range: 180.0,
            shoot_range: 520.0,
            attack_cooldown: 1.4,
            bullets_per_shot: 3,
            burst: true,
            burst_interval: 0.09,
            fan_spread: 0.12,
            projectile_speed: 260.0,
            projectile_spread: 0.04,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 2.8,
            projectile_color: [1.0, 0.9, 0.3, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::IceFlower => EnemyDef {
            name: "Ice Flower",
            hp: 450,
            speed: 0.0,
            accel: 0.0,
            radius: 18.0,
            size: 36.0,
            color: [0.6, 0.85, 1.0, 1.0],
            sprite: "images/sprIceFlowerIdle.png",
            score: 200,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 50,
            weapon_chance: 8,
            preferred_range: 0.0,
            shoot_range: 560.0,
            attack_cooldown: 2.0,
            bullets_per_shot: 8,
            burst: true,
            burst_interval: 0.1,
            fan_spread: 0.3,
            projectile_speed: 180.0,
            projectile_spread: 0.05,
            projectile_damage: 2,
            projectile_radius: 4.0,
            projectile_lifetime: 3.2,
            projectile_color: [0.6, 0.9, 1.0, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::SuperFrog => EnemyDef {
            name: "Super Frog",
            hp: 21,
            speed: 70.0,
            accel: 1100.0,
            radius: 11.0,
            size: 22.0,
            color: [0.3, 0.8, 0.35, 1.0],
            sprite: "images/sprSuperFrogIdle.png",
            score: 30,
            touch_damage: 0,
            rad_drop: 8,
            drop_chance: 25,
            weapon_chance: 2,
            preferred_range: 120.0,
            shoot_range: 380.0,
            attack_cooldown: 1.1,
            bullets_per_shot: 3,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.15,
            projectile_speed: 220.0,
            projectile_spread: 0.06,
            projectile_damage: 2,
            projectile_radius: 4.0,
            projectile_lifetime: 2.5,
            projectile_color: [0.4, 1.0, 0.4, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::RadMaggot => EnemyDef {
            name: "Rad Maggot",
            hp: 2,
            speed: 55.0,
            accel: 1000.0,
            radius: 8.0,
            size: 16.0,
            color: [0.4, 1.0, 0.3, 1.0],
            sprite: "images/sprRadMaggot.png",
            score: 8,
            touch_damage: 1,
            rad_drop: 2,
            drop_chance: 20,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::MeleeFake => EnemyDef {
            name: "Melee Fake",
            hp: 8,
            speed: 84.0,
            accel: 880.0,
            radius: 11.0,
            size: 22.0,
            color: [0.2, 0.18, 0.24, 1.0],
            sprite: "images/sprMeleeIdle.png",
            score: 15,
            touch_damage: 1,
            rad_drop: 8,
            drop_chance: 20,
            weapon_chance: 2,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::HostileHorror => EnemyDef {
            name: "Horror",
            hp: 60,
            speed: 45.0,
            accel: 900.0,
            radius: 18.0,
            size: 36.0,
            color: [0.6, 0.2, 0.8, 1.0],
            sprite: "images/sprEnemyHorrorIdle.png",
            score: 150,
            touch_damage: 4,
            rad_drop: 90,
            drop_chance: 60,
            weapon_chance: 10,
            preferred_range: 200.0,
            shoot_range: 520.0,
            attack_cooldown: 1.6,
            bullets_per_shot: 4,
            burst: true,
            burst_interval: 0.09,
            fan_spread: 0.2,
            projectile_speed: 200.0,
            projectile_spread: 0.06,
            projectile_damage: 3,
            projectile_radius: 5.0,
            projectile_lifetime: 3.0,
            projectile_color: [0.7, 0.3, 1.0, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::FiredMaggot => EnemyDef {
            name: "Fired Maggot",
            hp: 1,
            speed: 90.0,
            accel: 600.0,
            radius: 8.0,
            size: 16.0,
            color: [1.0, 0.5, 0.15, 1.0],
            sprite: "images/sprFiredMaggot.png",
            score: 5,
            touch_damage: 1,
            rad_drop: 1,
            drop_chance: 10,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::ScrapBossMissile => EnemyDef {
            name: "Scrap Missile",
            hp: 22,
            speed: 60.0,
            accel: 300.0,
            radius: 8.0,
            size: 16.0,
            color: [0.7, 0.7, 0.75, 1.0],
            sprite: "images/sprScrapBossMissileIdle.png",
            score: 5,
            touch_damage: 5,
            rad_drop: 0,
            drop_chance: 100,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 2.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::EliteInspector => EnemyDef {
            name: "Elite Inspector",
            hp: 40,
            speed: 105.0,
            accel: 900.0,
            radius: 10.0,
            size: 20.0,
            color: [0.5, 0.7, 1.0, 1.0],
            sprite: "images/sprEliteInspectorIdle.png",
            score: 25,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 20,
            weapon_chance: 0,
            preferred_range: 64.0,
            shoot_range: 160.0,
            attack_cooldown: 1.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 8,
            projectile_radius: 6.0,
            projectile_lifetime: 0.5,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::EliteShielder => EnemyDef {
            name: "Elite Shielder",
            hp: 100,
            speed: 90.0,
            accel: 900.0,
            radius: 11.0,
            size: 22.0,
            color: [0.5, 0.7, 1.0, 1.0],
            sprite: "images/sprEliteShielderIdle.png",
            score: 30,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 20,
            weapon_chance: 0,
            preferred_range: 150.0,
            shoot_range: 150.0,
            attack_cooldown: 1.0,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 45.0,
            projectile_spread: 0.0,
            projectile_damage: 8,
            projectile_radius: 5.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::ProtoStatue => EnemyDef {
            name: "Proto Statue",
            hp: 120,
            speed: 0.0,
            accel: 0.0,
            radius: 20.0,
            size: 40.0,
            color: [0.6, 0.6, 0.65, 1.0],
            sprite: "images/sprPStat1Idle.png",
            score: 50,
            touch_damage: 0,
            rad_drop: 0,
            drop_chance: 0,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Gator => EnemyDef {
            name: "Gator",
            hp: 12,
            speed: 30.0,
            accel: 900.0,
            radius: 13.0,
            size: 26.0,
            color: [0.25, 0.55, 0.28, 1.0],
            sprite: "images/sprGatorIdle.png",
            score: 18,
            touch_damage: 0,
            rad_drop: 8,
            drop_chance: 16,
            weapon_chance: 2,

            preferred_range: 90.0,
            shoot_range: 170.0,
            attack_cooldown: 1.5,
            bullets_per_shot: 6,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.22,

            projectile_speed: 360.0,
            projectile_spread: 0.436,
            projectile_damage: 1,
            projectile_radius: 3.5,
            projectile_lifetime: 0.6,
            projectile_color: [1.0, 0.75, 0.35, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::BuffGator => EnemyDef {
            name: "Buff Gator",
            hp: 30,
            speed: 34.0,
            accel: 950.0,
            radius: 16.0,
            size: 32.0,
            color: [0.3, 0.62, 0.32, 1.0],
            sprite: "images/sprBuffGatorIdle.png",
            score: 40,
            touch_damage: 0,
            rad_drop: 12,
            drop_chance: 32,
            weapon_chance: 0,
            preferred_range: 120.0,
            shoot_range: 260.0,
            attack_cooldown: 1.4,
            bullets_per_shot: 8,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.3,
            projectile_speed: 320.0,
            projectile_spread: 0.08,
            projectile_damage: 2,
            projectile_radius: 3.5,
            projectile_lifetime: 0.75,
            projectile_color: [1.0, 0.6, 0.25, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::Raven => EnemyDef {
            name: "Raven",
            hp: 10,
            speed: 85.0,
            accel: 1600.0,
            radius: 11.0,
            size: 22.0,
            color: [0.18, 0.18, 0.24, 1.0],
            sprite: "images/sprRavenIdle.png",
            score: 15,
            touch_damage: 0,
            rad_drop: 4,
            drop_chance: 14,
            weapon_chance: 0,
            preferred_range: 150.0,
            shoot_range: 480.0,
            attack_cooldown: 0.75,
            bullets_per_shot: 3,
            burst: true,
            burst_interval: 0.167,
            fan_spread: 0.0,
            projectile_speed: 120.0,
            projectile_spread: 0.14,
            projectile_damage: 3,
            projectile_radius: 3.5,
            projectile_lifetime: 2.6,
            projectile_color: [1.0, 0.32, 0.1, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::Salamander => EnemyDef {
            name: "Salamander",
            hp: 25,
            speed: 36.0,
            accel: 950.0,
            radius: 14.0,
            size: 30.0,
            color: [0.95, 0.45, 0.15, 1.0],
            sprite: "images/sprSalamanderIdle.png",
            score: 26,
            touch_damage: 1,
            rad_drop: 12,
            drop_chance: 18,
            weapon_chance: 3,

            preferred_range: 70.0,
            shoot_range: 150.0,
            attack_cooldown: 0.5,
            bullets_per_shot: 45,
            burst: true,
            burst_interval: 0.033,
            fan_spread: 0.05,
            projectile_speed: 180.0,
            projectile_spread: 0.12,
            projectile_damage: 2,
            projectile_radius: 4.5,
            projectile_lifetime: 0.9,
            projectile_color: [1.0, 0.45, 0.1, 1.0],
            projectile_size: 9.0,
            boss: false,
        },
        EnemyKind::MeleeBandit => EnemyDef {
            name: "Melee Bandit",
            hp: 7,
            speed: 95.0,
            accel: 2200.0,
            radius: 11.0,
            size: 22.0,
            color: [0.85, 0.35, 0.2, 1.0],
            sprite: "images/sprMeleeIdle.png",
            score: 12,
            touch_damage: 0,
            rad_drop: 8,
            drop_chance: 10,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::JungleBandit => EnemyDef {
            name: "Jungle Bandit",
            hp: 4,
            speed: 26.0,
            accel: 850.0,
            radius: 12.0,
            size: 24.0,
            color: [0.35, 0.6, 0.25, 1.0],
            sprite: "images/sprJungleBanditIdle.png",
            score: 10,
            touch_damage: 0,
            rad_drop: 2,
            drop_chance: 12,
            weapon_chance: 0,
            preferred_range: 100.0,
            shoot_range: 96.0,
            attack_cooldown: 1.65,
            bullets_per_shot: 6,
            burst: true,
            burst_interval: 0.133,
            fan_spread: 0.0,

            projectile_speed: 360.0,
            projectile_spread: 0.14,
            projectile_damage: 1,
            projectile_radius: 4.0,
            projectile_lifetime: 3.5,
            projectile_color: [0.55, 1.0, 0.35, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::BigMaggot => EnemyDef {
            name: "Big Maggot",
            hp: 22,
            speed: 60.0,
            accel: 1400.0,
            radius: 14.0,
            size: 30.0,
            color: [0.95, 0.5, 0.2, 1.0],
            sprite: "images/sprBigMaggotIdle.png",
            score: 20,
            touch_damage: 1,
            rad_drop: 10,
            drop_chance: 14,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::FastRat => EnemyDef {
            name: "Fast Rat",
            hp: 4,
            speed: 165.0,
            accel: 7000.0,
            radius: 9.0,
            size: 18.0,
            color: [0.5, 0.9, 0.4, 1.0],
            sprite: "images/sprFastRatIdle.png",
            score: 8,
            touch_damage: 2,
            rad_drop: 0,
            drop_chance: 0,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Ratking => EnemyDef {
            name: "Ratking",
            hp: 35,
            speed: 42.0,
            accel: 900.0,
            radius: 16.0,
            size: 32.0,
            color: [0.72, 0.55, 0.38, 1.0],
            sprite: "images/sprRatkingIdle.png",
            score: 35,
            touch_damage: 0,
            rad_drop: 20,
            drop_chance: 24,
            weapon_chance: 3,
            preferred_range: 190.0,
            shoot_range: 520.0,
            attack_cooldown: 1.5,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 210.0,
            projectile_spread: 0.05,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 2.6,
            projectile_color: [1.0, 0.65, 0.3, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::GoldScorpion => EnemyDef {
            name: "Gold Scorpion",
            hp: 40,
            speed: 30.0,
            accel: 850.0,
            radius: 15.0,
            size: 32.0,
            color: [0.95, 0.82, 0.25, 1.0],
            sprite: "images/sprGoldScorpionIdle.png",
            score: 50,
            touch_damage: 5,
            rad_drop: 30,
            drop_chance: 100,
            weapon_chance: 10,
            preferred_range: 130.0,
            shoot_range: 240.0,
            attack_cooldown: 0.8,
            bullets_per_shot: 10,
            burst: true,
            burst_interval: 0.033,
            fan_spread: 0.0,
            projectile_speed: 115.0,
            projectile_spread: 0.17,
            projectile_damage: 2,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.9, 0.3, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::LightningCrystal => EnemyDef {
            name: "Lightning Crystal",
            hp: 45,
            speed: 0.0,
            accel: 0.0,
            radius: 14.0,
            size: 30.0,
            color: [0.5, 0.85, 1.0, 1.0],
            sprite: "images/sprLightningCrystalIdle.png",
            score: 45,
            touch_damage: 20,
            rad_drop: 25,
            drop_chance: 30,
            weapon_chance: 5,
            preferred_range: 999.0,
            shoot_range: 96.0,
            attack_cooldown: 3.17,
            bullets_per_shot: 4,
            burst: true,
            burst_interval: 0.167,
            fan_spread: 0.0,
            projectile_speed: 340.0,
            projectile_spread: 0.02,
            projectile_damage: 4,
            projectile_radius: 3.5,
            projectile_lifetime: 1.1,
            projectile_color: [0.55, 0.85, 1.0, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::ExploFreak => EnemyDef {
            name: "Explo Freak",
            hp: 5,
            speed: 90.0,
            accel: 6000.0,
            radius: 12.0,
            size: 26.0,
            color: [0.95, 0.45, 0.2, 1.0],
            sprite: "images/sprExploFreakIdle.png",
            score: 18,
            touch_damage: 2,
            rad_drop: 10,
            drop_chance: 8,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::RhinoFreak => EnemyDef {
            name: "Rhino Freak",
            hp: 80,
            speed: 30.0,
            accel: 2600.0,
            radius: 17.0,
            size: 40.0,
            color: [0.55, 0.4, 0.7, 1.0],
            sprite: "images/sprRhinoFreakIdle.png",
            score: 50,
            touch_damage: 5,
            rad_drop: 20,
            drop_chance: 20,
            weapon_chance: 2,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::SnowTank => EnemyDef {
            name: "Snow Tank",
            hp: 50,
            speed: 22.0,
            accel: 500.0,
            radius: 18.0,
            size: 40.0,
            color: [0.55, 0.65, 0.78, 1.0],
            sprite: "images/sprSnowTankIdle.png",
            score: 55,
            touch_damage: 0,
            rad_drop: 10,
            drop_chance: 30,
            weapon_chance: 5,

            preferred_range: 230.0,
            shoot_range: 240.0,
            attack_cooldown: 1.83,
            bullets_per_shot: 16,
            burst: true,
            burst_interval: 0.066,
            fan_spread: 0.35,
            projectile_speed: 360.0,
            projectile_spread: 0.01,
            projectile_damage: 3,
            projectile_radius: 6.0,
            projectile_lifetime: 2.6,
            projectile_color: [1.0, 0.35, 0.15, 1.0],
            projectile_size: 11.0,
            boss: false,
        },
        EnemyKind::GoldSnowtank => EnemyDef {
            name: "Gold Snow Tank",
            hp: 70,
            speed: 24.0,
            accel: 520.0,
            radius: 18.0,
            size: 40.0,
            color: [0.95, 0.82, 0.25, 1.0],
            sprite: "images/sprGoldTankIdle.png",
            score: 110,
            touch_damage: 0,
            rad_drop: 13,
            drop_chance: 45,
            weapon_chance: 10,
            preferred_range: 250.0,
            shoot_range: 160.0,
            attack_cooldown: 0.58,
            bullets_per_shot: 16,
            burst: true,
            burst_interval: 0.066,
            fan_spread: 0.0,
            projectile_speed: 360.0,
            projectile_spread: 0.008,
            projectile_damage: 3,
            projectile_radius: 6.5,
            projectile_lifetime: 2.8,
            projectile_color: [1.0, 0.85, 0.2, 1.0],
            projectile_size: 12.0,
            boss: false,
        },
        EnemyKind::Guardian => EnemyDef {
            name: "Guardian",
            hp: 35,
            speed: 46.0,
            accel: 800.0,
            radius: 16.0,
            size: 34.0,
            color: [0.35, 0.85, 0.55, 1.0],
            sprite: "images/sprGuardianIdle.png",
            score: 40,
            touch_damage: 2,
            rad_drop: 11,
            drop_chance: 22,
            weapon_chance: 3,

            preferred_range: 180.0,
            shoot_range: 999.0,
            attack_cooldown: 0.4,
            bullets_per_shot: 3,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.7,
            projectile_speed: 60.0,
            projectile_spread: 0.04,
            projectile_damage: 5,
            projectile_radius: 6.0,
            projectile_lifetime: 3.4,
            projectile_color: [0.3, 1.0, 0.45, 1.0],
            projectile_size: 11.0,
            boss: false,
        },
        EnemyKind::ExploGuardian => EnemyDef {
            name: "Explo Guardian",
            hp: 50,
            speed: 52.0,
            accel: 900.0,
            radius: 15.0,
            size: 32.0,
            color: [0.95, 0.55, 0.25, 1.0],
            sprite: "images/sprExploGuardianIdle.png",
            score: 48,
            touch_damage: 2,
            rad_drop: 15,
            drop_chance: 0,
            weapon_chance: 10,
            preferred_range: 150.0,
            shoot_range: 90.0,
            attack_cooldown: 2.5,
            bullets_per_shot: 14,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.45,
            projectile_speed: 300.0,
            projectile_spread: 0.03,
            projectile_damage: 2,
            projectile_radius: 6.0,
            projectile_lifetime: 2.4,
            projectile_color: [1.0, 0.6, 0.2, 1.0],
            projectile_size: 10.0,
            boss: false,
        },
        EnemyKind::DogGuardian => EnemyDef {
            name: "Dog Guardian",
            hp: 160,
            speed: 100.0,
            accel: 3000.0,
            radius: 18.0,
            size: 40.0,
            color: [0.4, 0.75, 0.5, 1.0],
            sprite: "images/sprDogGuardianWalk.png",
            score: 90,
            touch_damage: 6,
            rad_drop: 20,
            drop_chance: 60,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::BoneFish => EnemyDef {
            name: "Bone Fish",
            hp: 8,
            speed: 105.0,
            accel: 4200.0,
            radius: 10.0,
            size: 20.0,
            color: [0.9, 0.88, 0.75, 1.0],
            sprite: "images/sprBoneFish1Idle.png",
            score: 12,
            touch_damage: 2,
            rad_drop: 2,
            drop_chance: 10,
            weapon_chance: 0,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Turtle => EnemyDef {
            name: "Turtle",
            hp: 15,
            speed: 30.0,
            accel: 900.0,
            radius: 13.0,
            size: 26.0,
            color: [0.45, 0.7, 0.4, 1.0],
            sprite: "images/sprTurtleIdle.png",
            score: 20,
            touch_damage: 4,
            rad_drop: 12,
            drop_chance: 25,
            weapon_chance: 3,

            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 1.7,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::Molefish => EnemyDef {
            name: "Molefish",
            hp: 6,
            speed: 30.0,
            accel: 850.0,
            radius: 11.0,
            size: 22.0,
            color: [0.65, 0.5, 0.35, 1.0],
            sprite: "images/sprMolefishIdle.png",
            score: 12,
            touch_damage: 0,
            rad_drop: 3,
            drop_chance: 12,
            weapon_chance: 0,
            preferred_range: 150.0,
            shoot_range: 999.0,
            attack_cooldown: 0.75,
            bullets_per_shot: 1,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 120.0,
            projectile_spread: 0.03,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.4, 0.1, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::Molesarge => EnemyDef {
            name: "Molesarge",
            hp: 14,
            speed: 32.0,
            accel: 900.0,
            radius: 12.0,
            size: 24.0,
            color: [0.72, 0.55, 0.38, 1.0],
            sprite: "images/sprMolesargeIdle.png",
            score: 22,
            touch_damage: 0,
            rad_drop: 6,
            drop_chance: 18,
            weapon_chance: 2,
            preferred_range: 170.0,
            shoot_range: 120.0,
            attack_cooldown: 1.08,

            bullets_per_shot: 5,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.52,
            projectile_speed: 330.0,
            projectile_spread: 0.02,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 3.0,
            projectile_color: [1.0, 0.5, 0.12, 1.0],
            projectile_size: 8.0,
            boss: false,
        },
        EnemyKind::FireBaller => EnemyDef {
            name: "Fire Baller",
            hp: 25,
            speed: 34.0,
            accel: 900.0,
            radius: 13.0,
            size: 28.0,
            color: [0.95, 0.4, 0.15, 1.0],
            sprite: "images/sprFireBallerIdle.png",
            score: 24,
            touch_damage: 0,
            rad_drop: 5,
            drop_chance: 0,
            weapon_chance: 10,

            preferred_range: 160.0,
            shoot_range: 999.0,
            attack_cooldown: 0.267,
            bullets_per_shot: 1,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 90.0,
            projectile_spread: 0.05,
            projectile_damage: 4,
            projectile_radius: 6.0,
            projectile_lifetime: 3.2,
            projectile_color: [1.0, 0.45, 0.08, 1.0],
            projectile_size: 11.0,
            boss: false,
        },
        EnemyKind::SuperFireBaller => EnemyDef {
            name: "Super Fire Baller",
            hp: 60,
            speed: 38.0,
            accel: 950.0,
            radius: 16.0,
            size: 34.0,
            color: [1.0, 0.5, 0.1, 1.0],
            sprite: "images/sprSuperFireBallerIdle.png",
            score: 45,
            touch_damage: 1,
            rad_drop: 15,
            drop_chance: 28,
            weapon_chance: 5,
            preferred_range: 180.0,
            shoot_range: 999.0,
            attack_cooldown: 0.267,
            bullets_per_shot: 3,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 95.0,
            projectile_spread: 0.04,
            projectile_damage: 4,
            projectile_radius: 7.0,
            projectile_lifetime: 3.4,
            projectile_color: [1.0, 0.55, 0.1, 1.0],
            projectile_size: 13.0,
            boss: false,
        },
        EnemyKind::Jock => EnemyDef {
            name: "Jock",
            hp: 25,
            speed: 44.0,
            accel: 1100.0,
            radius: 14.0,
            size: 30.0,
            color: [0.85, 0.3, 0.35, 1.0],
            sprite: "images/sprJockIdle.png",
            score: 26,
            touch_damage: 2,
            rad_drop: 8,
            drop_chance: 18,
            weapon_chance: 3,

            preferred_range: 190.0,
            shoot_range: 520.0,
            attack_cooldown: 0.267,
            bullets_per_shot: 1,
            burst: true,
            burst_interval: 0.3,
            fan_spread: 0.0,
            projectile_speed: 60.0,
            projectile_spread: 0.03,
            projectile_damage: 5,
            projectile_radius: 6.0,
            projectile_lifetime: 3.6,
            projectile_color: [1.0, 0.6, 0.2, 1.0],
            projectile_size: 10.0,
            boss: false,
        },
        EnemyKind::JungleFly => EnemyDef {
            name: "Jungle Fly",
            hp: 40,
            speed: 120.0,
            accel: 3600.0,
            radius: 13.0,
            size: 26.0,
            color: [0.55, 0.85, 0.3, 1.0],
            sprite: "images/sprJungleFlyIdle.png",
            score: 30,
            touch_damage: 5,
            rad_drop: 10,
            drop_chance: 20,
            weapon_chance: 2,

            preferred_range: 110.0,
            shoot_range: 380.0,
            attack_cooldown: 1.0,
            bullets_per_shot: 6,
            burst: true,
            burst_interval: 0.067,
            fan_spread: 0.0,
            projectile_speed: 150.0,
            projectile_spread: 0.07,
            projectile_damage: 3,
            projectile_radius: 4.0,
            projectile_lifetime: 1.6,
            projectile_color: [0.95, 0.55, 0.25, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::InvSpider => EnemyDef {
            name: "Cursed Spider",
            hp: 18,
            speed: 140.0,
            accel: 5200.0,
            radius: 10.0,
            size: 20.0,
            color: [0.35, 0.15, 0.45, 1.0],
            sprite: "images/sprInvSpiderIdle.png",
            score: 20,
            touch_damage: 3,
            rad_drop: 20,
            drop_chance: 18,
            weapon_chance: 2,
            preferred_range: 0.0,
            shoot_range: 0.0,
            attack_cooldown: 9.9,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::InvLaserCrystal => EnemyDef {
            name: "Cursed Laser Crystal",
            hp: 45,
            speed: 0.0,
            accel: 0.0,
            radius: 14.0,
            size: 30.0,
            color: [0.85, 0.3, 1.0, 1.0],
            sprite: "images/sprInvLaserCrystalIdle.png",
            score: 42,
            touch_damage: 20,
            rad_drop: 25,
            drop_chance: 32,
            weapon_chance: 6,
            preferred_range: 999.0,
            shoot_range: 160.0,
            attack_cooldown: 3.17,
            bullets_per_shot: 4,
            burst: true,
            burst_interval: 0.167,
            fan_spread: 0.0,
            projectile_speed: 330.0,
            projectile_spread: 0.01,
            projectile_damage: 4,
            projectile_radius: 3.5,
            projectile_lifetime: 1.2,
            projectile_color: [0.9, 0.3, 1.0, 1.0],
            projectile_size: 6.0,
            boss: false,
        },
        EnemyKind::PopoFreak => EnemyDef {
            name: "Popo Freak",
            hp: 30,
            speed: 115.0,
            accel: 2200.0,
            radius: 14.0,
            size: 30.0,
            color: [0.3, 0.5, 0.95, 1.0],
            sprite: "images/sprPopoFreakIdle.png",
            score: 50,
            touch_damage: 5,
            rad_drop: 25,
            drop_chance: 30,
            weapon_chance: 8,

            preferred_range: 130.0,
            shoot_range: 160.0,
            attack_cooldown: 0.75,
            bullets_per_shot: 16,
            burst: true,
            burst_interval: 0.033,
            fan_spread: 0.0,
            projectile_speed: 165.0,
            projectile_spread: 0.35,
            projectile_damage: 3,
            projectile_radius: 3.5,
            projectile_lifetime: 2.4,
            projectile_color: [0.5, 0.8, 1.0, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
        EnemyKind::MaggotSpawn => EnemyDef {
            name: "Maggot Spawn",
            hp: 12,
            speed: 0.0,
            accel: 0.0,
            radius: 14.0,
            size: 28.0,
            color: [0.9, 0.6, 0.3, 1.0],
            sprite: "images/sprMSpawnIdle.png",
            score: 15,
            touch_damage: 0,
            rad_drop: 5,
            drop_chance: 14,
            weapon_chance: 0,
            preferred_range: 999.0,
            shoot_range: 999.0,
            attack_cooldown: 2.6,
            bullets_per_shot: 0,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,
            projectile_speed: 0.0,
            projectile_spread: 0.0,
            projectile_damage: 0,
            projectile_radius: 0.0,
            projectile_lifetime: 0.0,
            projectile_color: [1.0, 1.0, 1.0, 1.0],
            projectile_size: 1.0,
            boss: false,
        },
        EnemyKind::IdpdInspector => EnemyDef {
            name: "IDPD Inspector",
            hp: 10,
            speed: 95.0,
            accel: 1400.0,
            radius: 12.0,
            size: 24.0,
            color: [0.45, 0.35, 0.9, 1.0],
            sprite: "images/sprInspectorIdle.png",
            score: 40,
            touch_damage: 0,

            rad_drop: 0,
            drop_chance: 22,
            weapon_chance: 6,
            preferred_range: 210.0,
            shoot_range: 560.0,
            attack_cooldown: 0.85,
            bullets_per_shot: 1,
            burst: false,
            burst_interval: 0.0,
            fan_spread: 0.0,

            projectile_speed: 480.0,
            projectile_spread: 0.1,
            projectile_damage: 3,
            projectile_radius: 3.5,
            projectile_lifetime: 2.2,
            projectile_color: [0.6, 0.55, 1.0, 1.0],
            projectile_size: 7.0,
            boss: false,
        },
    }
}
