//! nt id enums: byte-exact port of /home/ymsr/Documents/nt-recreated-bevy/src/game/content.rs. DO NOT EDIT BY HAND; fix upstream and re-port.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum EnemyKind {
    Maggot,
    Bandit,
    Scorpion,
    Assassin,
    Freak,
    BigBandit,
    BigBanditLoop,
    Throne,
    ThroneII,
    Hyper,
    Rat,
    BigRat,
    RobotGuard,
    Turret,
    SnowBandit,
    Wolf,
    BigDog,
    BigDogLoop,
    LilHunter,
    LilHunterLoop,
    IdpdGrunt,
    IdpdShield,
    IdpdElite,
    IdpdVan,

    Mom,

    FrogQueen,
    Technomancer,
    Captain,

    Ballguy,
    FrogEgg,
    Necromancer,

    Spider,
    Crystal,
    LaserCrystal,
    Sniper,
    Crab,

    Gator,
    BuffGator,
    Raven,
    Salamander,
    MeleeBandit,
    BigMaggot,
    FastRat,
    Ratking,
    GoldScorpion,
    LightningCrystal,
    ExploFreak,
    RhinoFreak,

    SnowTank,
    GoldSnowtank,
    Guardian,
    ExploGuardian,
    DogGuardian,

    JungleBandit,

    BoneFish,
    Turtle,
    Molefish,
    Molesarge,
    FireBaller,
    SuperFireBaller,
    Jock,
    JungleFly,
    InvSpider,
    InvLaserCrystal,
    PopoFreak,
    MaggotSpawn,

    IdpdInspector,

    OldGuardian,

    PalaceGuardian,

    Mimic,
    SuperMimic,
    WepMimic,
    YvBoss,
    CrownGuardian,
    IceFlower,
    SuperFrog,
    RadMaggot,
    MeleeFake,
    HostileHorror,
    FiredMaggot,
    /// GML `ScrapBossMissile`: homing missile with a trail gun.
    ScrapBossMissile,
    /// GML `EliteInspector`: control-drag field, baton dash-slash, PopoNade.
    EliteInspector,
    /// GML `EliteShielder`: plasma bursts, `EliteShield` carry/teleport.
    EliteShielder,
    /// GML `ProtoStatue`: vault guardian (IDPD phases, vault portal).
    ProtoStatue,
}

impl EnemyKind {
    pub fn from_u16(v: u16) -> Option<Self> {
        const ALL: &[EnemyKind] = &[
            EnemyKind::Maggot,
            EnemyKind::Bandit,
            EnemyKind::Scorpion,
            EnemyKind::Assassin,
            EnemyKind::Freak,
            EnemyKind::BigBandit,
            EnemyKind::BigBanditLoop,
            EnemyKind::Throne,
            EnemyKind::ThroneII,
            EnemyKind::Hyper,
            EnemyKind::Rat,
            EnemyKind::BigRat,
            EnemyKind::RobotGuard,
            EnemyKind::Turret,
            EnemyKind::SnowBandit,
            EnemyKind::Wolf,
            EnemyKind::BigDog,
            EnemyKind::BigDogLoop,
            EnemyKind::LilHunter,
            EnemyKind::LilHunterLoop,
            EnemyKind::IdpdGrunt,
            EnemyKind::IdpdShield,
            EnemyKind::IdpdElite,
            EnemyKind::IdpdVan,
            EnemyKind::Mom,
            EnemyKind::FrogQueen,
            EnemyKind::Technomancer,
            EnemyKind::Captain,
            EnemyKind::Ballguy,
            EnemyKind::FrogEgg,
            EnemyKind::Necromancer,
            EnemyKind::Spider,
            EnemyKind::Crystal,
            EnemyKind::LaserCrystal,
            EnemyKind::Sniper,
            EnemyKind::Crab,
            EnemyKind::Gator,
            EnemyKind::BuffGator,
            EnemyKind::Raven,
            EnemyKind::Salamander,
            EnemyKind::MeleeBandit,
            EnemyKind::BigMaggot,
            EnemyKind::FastRat,
            EnemyKind::Ratking,
            EnemyKind::GoldScorpion,
            EnemyKind::LightningCrystal,
            EnemyKind::ExploFreak,
            EnemyKind::RhinoFreak,
            EnemyKind::SnowTank,
            EnemyKind::GoldSnowtank,
            EnemyKind::Guardian,
            EnemyKind::ExploGuardian,
            EnemyKind::DogGuardian,
            EnemyKind::JungleBandit,
            EnemyKind::BoneFish,
            EnemyKind::Turtle,
            EnemyKind::Molefish,
            EnemyKind::Molesarge,
            EnemyKind::FireBaller,
            EnemyKind::SuperFireBaller,
            EnemyKind::Jock,
            EnemyKind::JungleFly,
            EnemyKind::InvSpider,
            EnemyKind::InvLaserCrystal,
            EnemyKind::PopoFreak,
            EnemyKind::MaggotSpawn,
            EnemyKind::IdpdInspector,
            EnemyKind::OldGuardian,
            EnemyKind::PalaceGuardian,
            EnemyKind::Mimic,
            EnemyKind::SuperMimic,
            EnemyKind::WepMimic,
            EnemyKind::YvBoss,
            EnemyKind::CrownGuardian,
            EnemyKind::IceFlower,
            EnemyKind::SuperFrog,
            EnemyKind::RadMaggot,
            EnemyKind::MeleeFake,
            EnemyKind::HostileHorror,
            EnemyKind::FiredMaggot,
            EnemyKind::ScrapBossMissile,
            EnemyKind::EliteInspector,
            EnemyKind::EliteShielder,
            EnemyKind::ProtoStatue,
        ];
        ALL.get(v as usize).copied()
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
pub enum UltraMutationId {
    FishGunWarrant,
    FishConfiscate,
    CrystalFortress,
    CrystalJuggernaut,
    EyesMonsterStyle,
    EyesProjectileStyle,
    MeltingBrainCapacity,
    MeltingDetachment,
    PlantTrapper,
    PlantKiller,
    VenuzBack2Bizniz,
    VenuzGunGod,
    SteroidsAmbidextrous,
    SteroidsGetArmed,
    RobotRefinedTaste,
    RobotRegurgitate,
    ChickenHarderToKill,
    ChickenDetermination,
    RebelPersonalGuard,
    RebelRiot,
    HorrorStalker,
    HorrorAnomaly,
    RogueSuperBlastArmor,
    RoguePortalStrike,
    BigDogHeavyArtillery,
    BigDogGuardian,
    SkeletonBloodArmor,
    SkeletonNecromancy,
    FrogToxicLord,
    FrogSwampBody,
    CuzHoarder,
    CuzQuickSwap,
    /// GML `UltraSkill.Emotional` (Cuz B): cry tears + ammo scale.
    CuzEmotional,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
pub enum MutationId {
    RhinoSkin,
    PlutoniumHunger,
    TriggerFingers,
    RabbitPaw,
    SecondStomach,
    ScarierFace,
    BoilingVeins,
    ImpactWrists,
    ExtraFeet,
    Bloodlust,
    LuckyShot,
    GammaGuts,
    BackMuscle,
    Euphoria,
    LongArms,
    Stress,
    EagleEyes,
    OpenMind,
    HeavyHeart,
    StrongSpirit,
    SharpTeeth,
    LastWish,

    BoltMarrow,
    Hammerhead,
    LaserBrain,
    RecycleGland,
    ShotgunShoulders,
    ThroneButt,
    Patience,
}
