#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum AmmoType {
    None = 0,
    Bullets = 1,
    Shells = 2,
    Bolts = 3,
    Explosives = 4,
    Energy = 5,
}

impl AmmoType {
    pub const fn from_u8(v: u8) -> Self {
        match v {
            0 => Self::None,
            1 => Self::Bullets,
            2 => Self::Shells,
            3 => Self::Bolts,
            4 => Self::Explosives,
            5 => Self::Energy,
            _ => Self::None,
        }
    }
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::None => "None",
            Self::Bullets => "Bullets",
            Self::Shells => "Shells",
            Self::Bolts => "Bolts",
            Self::Explosives => "Explosives",
            Self::Energy => "Energy",
        }
    }
}

#[derive(Clone, Copy, Debug)]
#[allow(dead_code)]
pub struct WeaponData {
    pub id: u8,
    pub wep_name: &'static str,
    pub wep_type: AmmoType,
    pub wep_auto: bool,
    pub wep_cost: u8,
    pub wep_area: i8,
    pub wep_load: u16,
    pub wep_text: &'static str,
    pub wep_gold: bool,
    pub wep_rads: u8,
    pub wep_mele: bool,
    pub wep_naim: bool,
    pub wep_sprt: &'static str,
    pub wep_swap: &'static str,
    pub wep_lout: Option<&'static str>,
}

pub const MAXWEP: usize = 128;
pub const WEAPON_COUNT: usize = 129;

pub const WEAPONS: [WeaponData; WEAPON_COUNT] = [
    WeaponData {
        id: 0,
        wep_name: "",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 1,
        wep_area: -1,
        wep_load: 1,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "mskNone",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 1,
        wep_name: "REVOLVER",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 1,
        wep_area: -1,
        wep_load: 6,
        wep_text: "trusty old @wrevolver@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprRevolver",
        wep_swap: "sndSwapPistol",
        wep_lout: Some("sprRevolverLoadout"),
    },
    WeaponData {
        id: 2,
        wep_name: "TRIPLE MACHINEGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 3,
        wep_area: 4,
        wep_load: 4,
        wep_text: "@wtriple machinegun@s, so much fun",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprTripleMachinegun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 3,
        wep_name: "WRENCH",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 1,
        wep_load: 22,
        wep_text: "hell",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprWrench",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 4,
        wep_name: "MACHINEGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 0,
        wep_load: 5,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprMachinegun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 5,
        wep_name: "SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 0,
        wep_load: 17,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 6,
        wep_name: "CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 1,
        wep_load: 26,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 7,
        wep_name: "GRENADE LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 1,
        wep_load: 20,
        wep_text: "be careful with those @wgrenades@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 8,
        wep_name: "DOUBLE SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 5,
        wep_load: 28,
        wep_text: "@wdouble shotgun@s, double fun",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSuperShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 9,
        wep_name: "MINIGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 6,
        wep_load: 1,
        wep_text: "time to rain @ybullets@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprMinigun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 10,
        wep_name: "AUTO SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 6,
        wep_load: 4,
        wep_text: "just hold down the trigger",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprAutoShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 11,
        wep_name: "AUTO CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 7,
        wep_load: 8,
        wep_text: "225 @ybolts@s per minute",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprAutoCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 12,
        wep_name: "SUPER CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 5,
        wep_area: 8,
        wep_load: 30,
        wep_text: "5 @ybolts@s per shot",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSuperCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 13,
        wep_name: "SHOVEL",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 4,
        wep_load: 35,
        wep_text: "dig",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprShovel",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 14,
        wep_name: "BAZOOKA",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 30,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprBazooka",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 15,
        wep_name: "STICKY LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 7,
        wep_load: 25,
        wep_text: "dont touch @wsticky nades@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprStickyNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 16,
        wep_name: "SMG",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 3,
        wep_load: 3,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSmg",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 17,
        wep_name: "ASSAULT RIFLE",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 2,
        wep_load: 11,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprARifle",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 18,
        wep_name: "DISC GUN",
        wep_type: AmmoType::Bolts,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 3,
        wep_load: 8,
        wep_text: "we hereby sincerely apologize",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprDiscGun",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 19,
        wep_name: "LASER PISTOL",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 2,
        wep_load: 9,
        wep_text: "futuristic weaponry",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLaserGun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 20,
        wep_name: "LASER RIFLE",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 7,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLaserRifle",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 21,
        wep_name: "SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 2,
        wep_load: 22,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 22,
        wep_name: "GATLING SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 9,
        wep_load: 7,
        wep_text: "time to gatle",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGatlingSlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 23,
        wep_name: "ASSAULT SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 5,
        wep_load: 35,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprAssaultSlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 24,
        wep_name: "ENERGY SWORD",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 10,
        wep_load: 12,
        wep_text: "zzzwwoonggg",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprEnergySword",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 25,
        wep_name: "SUPER SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 5,
        wep_area: 10,
        wep_load: 32,
        wep_text: "no need to aim",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSuperSlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 26,
        wep_name: "HYPER RIFLE",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 5,
        wep_area: 8,
        wep_load: 3,
        wep_text: "@bhyper@s time",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHyperRifle",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 27,
        wep_name: "SCREWDRIVER",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 2,
        wep_load: 11,
        wep_text: "@wscrewdriver@s will fix it",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprScrewDriver",
        wep_swap: "sndSwapSword",
        wep_lout: None,
    },
    WeaponData {
        id: 28,
        wep_name: "LASER MINIGUN",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 9,
        wep_load: 2,
        wep_text: "energy bill off the charts",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLaserMinigun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 29,
        wep_name: "BLOOD LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 10,
        wep_load: 12,
        wep_text: "built with spare parts",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprBloodNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 30,
        wep_name: "SPLINTER GUN",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 19,
        wep_text: "this will hurt",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSplinterGun",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 31,
        wep_name: "TOXIC BOW",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 29,
        wep_text: "hold breath while firing",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprToxicBow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 32,
        wep_name: "SENTRY GUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 24,
        wep_area: -1,
        wep_load: 60,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSentryGun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 33,
        wep_name: "WAVE GUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 10,
        wep_load: 17,
        wep_text: "shoot em up",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprWaveGun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 34,
        wep_name: "PLASMA GUN",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 5,
        wep_load: 16,
        wep_text: "fun fun",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprPlasmaGun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 35,
        wep_name: "PLASMA CANNON",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 8,
        wep_area: 11,
        wep_load: 40,
        wep_text: "fun fun fun fun",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprPlasmaCannon",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 36,
        wep_name: "ENERGY HAMMER",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 5,
        wep_area: 10,
        wep_load: 20,
        wep_text: "break a leg",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: true,
        wep_sprt: "sprEnergyHammer",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 37,
        wep_name: "JACKHAMMER",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 12,
        wep_text: "break some legs",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprJackHammer",
        wep_swap: "sndSwapMotorized",
        wep_lout: None,
    },
    WeaponData {
        id: 38,
        wep_name: "FLAK CANNON",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 6,
        wep_load: 26,
        wep_text: "10/10",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprFlakCannon",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 39,
        wep_name: "GOLDEN REVOLVER",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 1,
        wep_area: -1,
        wep_load: 5,
        wep_text: "@yB-)",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldRevolver",
        wep_swap: "sndSwapPistol",
        wep_lout: Some("sprGoldRevolverLoadout"),
    },
    WeaponData {
        id: 40,
        wep_name: "GOLDEN WRENCH",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 18,
        wep_load: 18,
        wep_text: "shiny @ywrench@s",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprGoldWrench",
        wep_swap: "sndSwapHammer",
        wep_lout: Some("sprGoldWrenchLoadout"),
    },
    WeaponData {
        id: 41,
        wep_name: "GOLDEN MACHINEGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 18,
        wep_load: 5,
        wep_text: "expensive @ymachinegun@s",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldMachinegun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: Some("sprGoldMachinegunLoadout"),
    },
    WeaponData {
        id: 42,
        wep_name: "GOLDEN SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 18,
        wep_load: 17,
        wep_text: "beautiful @yshotgun@s",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: Some("sprGoldShotgunLoadout"),
    },
    WeaponData {
        id: 43,
        wep_name: "GOLDEN CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 18,
        wep_load: 23,
        wep_text: "@yvelvet handles",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: Some("sprGoldCrossbowLoadout"),
    },
    WeaponData {
        id: 44,
        wep_name: "GOLDEN GRENADE LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 18,
        wep_load: 20,
        wep_text: "even the @wgrenades@s are @ygold@s",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: Some("sprGoldGrenadeLauncherLoadout"),
    },
    WeaponData {
        id: 45,
        wep_name: "GOLDEN LASER PISTOL",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 18,
        wep_load: 8,
        wep_text: "@ythis thing gets hot",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldLaserGun",
        wep_swap: "sndSwapEnergy",
        wep_lout: Some("sprGoldLaserPistolLoadout"),
    },
    WeaponData {
        id: 46,
        wep_name: "CHICKEN SWORD",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: -1,
        wep_load: 18,
        wep_text: "chicken loves her @wsword@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprSword",
        wep_swap: "sndSwapSword",
        wep_lout: Some("sprChickenSwordLoadout"),
    },
    WeaponData {
        id: 47,
        wep_name: "NUKE LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 10,
        wep_load: 50,
        wep_text: "this is what started it all",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprNukeLauncher",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 48,
        wep_name: "ION CANNON",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 6,
        wep_area: -1,
        wep_load: 10,
        wep_text: "death from above",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprIonCannon",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 49,
        wep_name: "QUADRUPLE MACHINEGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 4,
        wep_area: 12,
        wep_load: 4,
        wep_text: "the future is here",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprQuadrupleMachinegun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 50,
        wep_name: "FLAMETHROWER",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 12,
        wep_text: "burn burn burn",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprFlameThrower",
        wep_swap: "sndSwapFlame",
        wep_lout: None,
    },
    WeaponData {
        id: 51,
        wep_name: "DRAGON",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 13,
        wep_load: 7,
        wep_text: "hot breath",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprDragon",
        wep_swap: "sndSwapDragon",
        wep_lout: None,
    },
    WeaponData {
        id: 52,
        wep_name: "FLARE GUN",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 6,
        wep_load: 25,
        wep_text: "signal for help",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprFlareGun",
        wep_swap: "sndSwapFlame",
        wep_lout: None,
    },
    WeaponData {
        id: 53,
        wep_name: "ENERGY SCREWDRIVER",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 9,
        wep_load: 4,
        wep_text: "future fixing",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprEnergyScrewDriver",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 54,
        wep_name: "HYPER LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 14,
        wep_load: 7,
        wep_text: "point and click",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHyperLauncher",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 55,
        wep_name: "LASER CANNON",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 3,
        wep_area: 7,
        wep_load: 30,
        wep_text: "oh @wlaser cannon@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLaserCannon",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 56,
        wep_name: "RUSTY REVOLVER",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 1,
        wep_area: -1,
        wep_load: 7,
        wep_text: "rusty old @wrevolver@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprRustyRevolver",
        wep_swap: "sndSwapPistol",
        wep_lout: Some("sprRustyRevolverLoadout"),
    },
    WeaponData {
        id: 57,
        wep_name: "LIGHTNING PISTOL",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 6,
        wep_load: 11,
        wep_text: "thunder",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLightningPistol",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 58,
        wep_name: "LIGHTNING RIFLE",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 8,
        wep_load: 24,
        wep_text: "a storm is coming",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLightningRifle",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 59,
        wep_name: "LIGHTNING SHOTGUN",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 9,
        wep_load: 20,
        wep_text: "hurricane",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLightningShotgun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 60,
        wep_name: "SUPER FLAK CANNON",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 8,
        wep_area: 12,
        wep_load: 64,
        wep_text: "11/10",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSuperFlakCannon",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 61,
        wep_name: "SAWED-OFF SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 6,
        wep_load: 28,
        wep_text: "a true @wmelee weapon@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSawnOffShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 62,
        wep_name: "SPLINTER PISTOL",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 6,
        wep_load: 8,
        wep_text: "watch your fingers",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSplinterPistol",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 63,
        wep_name: "SUPER SPLINTER GUN",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 8,
        wep_load: 28,
        wep_text: "terror",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprHeavySplinterGun",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 64,
        wep_name: "LIGHTNING SMG",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 13,
        wep_load: 7,
        wep_text: "heavy weather",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprLightningSMG",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 65,
        wep_name: "SMART GUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 10,
        wep_load: 3,
        wep_text: "it thinks",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSmartGun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 66,
        wep_name: "HEAVY CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 5,
        wep_load: 40,
        wep_text: "a true burden",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavyCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 67,
        wep_name: "BLOOD HAMMER",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 10,
        wep_load: 21,
        wep_text: "drip",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprBloodHammer",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 68,
        wep_name: "LIGHTNING CANNON",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 8,
        wep_area: 13,
        wep_load: 34,
        wep_text: "typhoon",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprLightningCannon",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 69,
        wep_name: "POP GUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 3,
        wep_load: 2,
        wep_text: "how does this thing even work",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprPopGun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 70,
        wep_name: "PLASMA RIFLE",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 8,
        wep_load: 10,
        wep_text: "fun fun fun",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprPlasmaRifle",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 71,
        wep_name: "POP RIFLE",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 4,
        wep_load: 9,
        wep_text: "let's hope this works",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprPopRifle",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 72,
        wep_name: "TOXIC LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 16,
        wep_text: "don't breathe",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprToxicNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 73,
        wep_name: "FLAME CANNON",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 4,
        wep_area: 13,
        wep_load: 44,
        wep_text: "inferno",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprFlameCannon",
        wep_swap: "sndSwapFlame",
        wep_lout: None,
    },
    WeaponData {
        id: 74,
        wep_name: "LIGHTNING HAMMER",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 11,
        wep_load: 32,
        wep_text: "shock value",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprLightningHammer",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 75,
        wep_name: "FLAME SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 5,
        wep_load: 20,
        wep_text: "a burning sensation",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprFlameShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 76,
        wep_name: "DOUBLE FLAME SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 7,
        wep_load: 28,
        wep_text: "incinerate them",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprDoubleFlameShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 77,
        wep_name: "AUTO FLAME SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 10,
        wep_load: 5,
        wep_text: "raining fire",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprAutoFlameShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 78,
        wep_name: "CLUSTER LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 7,
        wep_load: 26,
        wep_text: "small explosions",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprClusterNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 79,
        wep_name: "GRENADE SHOTGUN",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 7,
        wep_load: 16,
        wep_text: "don't get too close",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprNadeShotgun",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 80,
        wep_name: "GRENADE RIFLE",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 9,
        wep_load: 10,
        wep_text: "distant explosions",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprNadeRifle",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 81,
        wep_name: "ROGUE RIFLE",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 2,
        wep_area: -1,
        wep_load: 6,
        wep_text: "loose cannon",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprRogueRifle",
        wep_swap: "sndSwapPistol",
        wep_lout: Some("sprRogueRifleLoadout"),
    },
    WeaponData {
        id: 82,
        wep_name: "PARTY GUN",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 0,
        wep_area: -1,
        wep_load: 20,
        wep_text: "woohoo!",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprPartyGun",
        wep_swap: "sndSwapFlame",
        wep_lout: None,
    },
    WeaponData {
        id: 83,
        wep_name: "DOUBLE MINIGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 14,
        wep_load: 1,
        wep_text: "sea of @ybullets@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprDoubleMinigun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 84,
        wep_name: "GATLING BAZOOKA",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 12,
        wep_load: 10,
        wep_text: "explosions",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGatlingBazooka",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 85,
        wep_name: "AUTO GRENADE SHOTGUN",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 14,
        wep_load: 8,
        wep_text: "stay away",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprAutoNadeShotgun",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 86,
        wep_name: "ULTRA REVOLVER",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 21,
        wep_load: 4,
        wep_text: "feeling @gultra@s",
        wep_gold: false,
        wep_rads: 4,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprUltraRevolver",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 87,
        wep_name: "ULTRA LASER PISTOL",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 21,
        wep_load: 8,
        wep_text: "unstoppable",
        wep_gold: false,
        wep_rads: 14,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprUltraLaserGun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 88,
        wep_name: "SLEDGEHAMMER",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 4,
        wep_load: 35,
        wep_text: "steel on steel",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprHammer",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 89,
        wep_name: "HEAVY REVOLVER",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 9,
        wep_load: 5,
        wep_text: "heavy @ybullets@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavyRevolver",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 90,
        wep_name: "HEAVY MACHINEGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 10,
        wep_load: 5,
        wep_text: "get some",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavyMachinegun",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 91,
        wep_name: "HEAVY SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 10,
        wep_load: 13,
        wep_text: "get out of here",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavySlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 92,
        wep_name: "ULTRA SHOVEL",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 21,
        wep_load: 15,
        wep_text: "perfection",
        wep_gold: false,
        wep_rads: 16,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprUltraShovel",
        wep_swap: "sndSwapHammer",
        wep_lout: None,
    },
    WeaponData {
        id: 93,
        wep_name: "ULTRA SHOTGUN",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 21,
        wep_load: 12,
        wep_text: "no chance",
        wep_gold: false,
        wep_rads: 14,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprUltraShotgun",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 94,
        wep_name: "ULTRA CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 21,
        wep_load: 11,
        wep_text: "nowhere to hide",
        wep_gold: false,
        wep_rads: 12,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprUltraCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 95,
        wep_name: "ULTRA GRENADE LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 21,
        wep_load: 16,
        wep_text: "they'll come",
        wep_gold: false,
        wep_rads: 16,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprUltraNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 96,
        wep_name: "PLASMA MINIGUN",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 15,
        wep_load: 3,
        wep_text: "all the fun",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprPlasmaMinigun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 97,
        wep_name: "DEVASTATOR",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 8,
        wep_area: 16,
        wep_load: 60,
        wep_text: "...",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprDevastator",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 98,
        wep_name: "GOLDEN PLASMA GUN",
        wep_type: AmmoType::Energy,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 20,
        wep_load: 16,
        wep_text: "@ybeautiful alloys",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldPlasmaGun",
        wep_swap: "sndSwapEnergy",
        wep_lout: Some("sprGoldPlasmaGunLoadout"),
    },
    WeaponData {
        id: 99,
        wep_name: "GOLDEN SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 20,
        wep_load: 20,
        wep_text: "@ypriceless hardwood",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldSlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: Some("sprGoldSluggerLoadout"),
    },
    WeaponData {
        id: 100,
        wep_name: "GOLDEN SPLINTER GUN",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 20,
        wep_load: 19,
        wep_text: "even the @yammo@s is expensive",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldSplinterGun",
        wep_swap: "sndSwapBow",
        wep_lout: Some("sprGoldSplintergunLoadout"),
    },
    WeaponData {
        id: 101,
        wep_name: "GOLDEN SCREWDRIVER",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: 20,
        wep_load: 9,
        wep_text: "@yivory handle",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprGoldScrewdriver",
        wep_swap: "sndSwapSword",
        wep_lout: Some("sprGoldScrewdriverLoadout"),
    },
    WeaponData {
        id: 102,
        wep_name: "GOLDEN BAZOOKA",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 20,
        wep_load: 28,
        wep_text: "worth its weight in @ygold",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldBazooka",
        wep_swap: "sndSwapExplosive",
        wep_lout: Some("sprGoldBazookaLoadout"),
    },
    WeaponData {
        id: 103,
        wep_name: "GOLDEN ASSAULT RIFLE",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 20,
        wep_load: 9,
        wep_text: "bursts of @ygold",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldARifle",
        wep_swap: "sndSwapMachinegun",
        wep_lout: Some("sprGoldAssaultRifleLoadout"),
    },
    WeaponData {
        id: 104,
        wep_name: "SUPER DISC GUN",
        wep_type: AmmoType::Bolts,
        wep_auto: true,
        wep_cost: 5,
        wep_area: 11,
        wep_load: 12,
        wep_text: "many apologies",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSuperDiscGun",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 105,
        wep_name: "HEAVY AUTO CROSSBOW",
        wep_type: AmmoType::Bolts,
        wep_auto: true,
        wep_cost: 2,
        wep_area: 16,
        wep_load: 13,
        wep_text: "weighs you down",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavyAutoCrossbow",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 106,
        wep_name: "HEAVY ASSAULT RIFLE",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 6,
        wep_area: 13,
        wep_load: 9,
        wep_text: "go for it",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavyARifle",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 107,
        wep_name: "BLOOD CANNON",
        wep_type: AmmoType::Explosives,
        wep_auto: true,
        wep_cost: 4,
        wep_area: 12,
        wep_load: 19,
        wep_text: "fully organic",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprBloodCannon",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 108,
        wep_name: "DOG SPIN ATTACK",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 15,
        wep_area: -1,
        wep_load: 120,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "mskNone",
        wep_swap: "sndSwapExplosive",
        wep_lout: Some("mskNone"),
    },
    WeaponData {
        id: 109,
        wep_name: "DOG MISSILE",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 1,
        wep_area: -1,
        wep_load: 1,
        wep_text: "",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "mskNone",
        wep_swap: "sndSwapExplosive",
        wep_lout: Some("mskNone"),
    },
    WeaponData {
        id: 110,
        wep_name: "INCINERATOR",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 3,
        wep_area: 16,
        wep_load: 2,
        wep_text: "...",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprIncinerator",
        wep_swap: "sndSwapMachinegun",
        wep_lout: None,
    },
    WeaponData {
        id: 111,
        wep_name: "SUPER PLASMA CANNON",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 24,
        wep_area: 16,
        wep_load: 260,
        wep_text: "comedy",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSuperPlasmaCannon",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 112,
        wep_name: "SEEKER PISTOL",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 7,
        wep_load: 16,
        wep_text: "no hiding",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprSeekerPistol",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 113,
        wep_name: "SEEKER SHOTGUN",
        wep_type: AmmoType::Bolts,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 9,
        wep_load: 28,
        wep_text: "no escape",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSeekerShotgun",
        wep_swap: "sndSwapBow",
        wep_lout: None,
    },
    WeaponData {
        id: 114,
        wep_name: "ERASER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 8,
        wep_load: 20,
        wep_text: "goodbye head",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprEraser",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 115,
        wep_name: "GUITAR",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: -1,
        wep_load: 21,
        wep_text: "there's no reason to fight",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprGuitar",
        wep_swap: "sndSwapGuitar",
        wep_lout: None,
    },
    WeaponData {
        id: 116,
        wep_name: "BOUNCER SMG",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 6,
        wep_load: 3,
        wep_text: "watch your back",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprBouncerSMG",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 117,
        wep_name: "BOUNCER SHOTGUN",
        wep_type: AmmoType::Bullets,
        wep_auto: true,
        wep_cost: 6,
        wep_area: 6,
        wep_load: 18,
        wep_text: "they're everywhere",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprBouncerShotgun",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 118,
        wep_name: "HYPER SLUGGER",
        wep_type: AmmoType::Shells,
        wep_auto: false,
        wep_cost: 1,
        wep_area: 15,
        wep_load: 10,
        wep_text: "time to hyper",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHyperSlugger",
        wep_swap: "sndSwapShotgun",
        wep_lout: None,
    },
    WeaponData {
        id: 119,
        wep_name: "SUPER BAZOOKA",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 5,
        wep_area: 11,
        wep_load: 40,
        wep_text: "this is getting silly",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprSuperBazooka",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 120,
        wep_name: "FROG PISTOL",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 2,
        wep_area: -1,
        wep_load: 7,
        wep_text: "always",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprFrogBlaster",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 121,
        wep_name: "BLACK SWORD",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: -1,
        wep_load: 16,
        wep_text: "chicken fears her @wsword@s",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprBlackSword",
        wep_swap: "sndSwapSword",
        wep_lout: None,
    },
    WeaponData {
        id: 122,
        wep_name: "GOLDEN NUKE LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 3,
        wep_area: 12,
        wep_load: 40,
        wep_text: "@yexcessive",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprGoldNukeLauncher",
        wep_swap: "sndSwapExplosive",
        wep_lout: Some("sprGoldNukeLauncherLoadout"),
    },
    WeaponData {
        id: 123,
        wep_name: "GOLDEN DISC GUN",
        wep_type: AmmoType::Bolts,
        wep_auto: true,
        wep_cost: 1,
        wep_area: 12,
        wep_load: 8,
        wep_text: "@ygo in style",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldDiscgun",
        wep_swap: "sndSwapBow",
        wep_lout: Some("sprGoldDiscgunLoadout"),
    },
    WeaponData {
        id: 124,
        wep_name: "HEAVY GRENADE LAUNCHER",
        wep_type: AmmoType::Explosives,
        wep_auto: false,
        wep_cost: 2,
        wep_area: 8,
        wep_load: 26,
        wep_text: "watch out",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprHeavyNader",
        wep_swap: "sndSwapExplosive",
        wep_lout: None,
    },
    WeaponData {
        id: 125,
        wep_name: "GUN GUN",
        wep_type: AmmoType::Energy,
        wep_auto: false,
        wep_cost: 40,
        wep_area: 19,
        wep_load: 90,
        wep_text: "make it",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: true,
        wep_sprt: "sprGunGun",
        wep_swap: "sndSwapEnergy",
        wep_lout: None,
    },
    WeaponData {
        id: 126,
        wep_name: "EGGPLANT",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: -1,
        wep_load: 15,
        wep_text: "CAREFUL",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprEggplant",
        wep_swap: "sndSwapPistol",
        wep_lout: None,
    },
    WeaponData {
        id: 127,
        wep_name: "GOLDEN FROG PISTOL",
        wep_type: AmmoType::Bullets,
        wep_auto: false,
        wep_cost: 1,
        wep_area: -1,
        wep_load: 6,
        wep_text: "ALWAYS BELIEVE IN YOUR SOUL",
        wep_gold: true,
        wep_rads: 0,
        wep_mele: false,
        wep_naim: false,
        wep_sprt: "sprGoldFrogBlaster",
        wep_swap: "sndSwapPistol",
        wep_lout: Some("sprGoldToxicGunLoadout"),
    },
    WeaponData {
        id: 128,
        wep_name: "ELECTRIC GUITAR",
        wep_type: AmmoType::None,
        wep_auto: false,
        wep_cost: 0,
        wep_area: -1,
        wep_load: 21,
        wep_text: "fish can rock and roll",
        wep_gold: false,
        wep_rads: 0,
        wep_mele: true,
        wep_naim: false,
        wep_sprt: "sprElectricGuitar",
        wep_swap: "sndSwapElectricGuitar",
        wep_lout: None,
    },
];

pub const WEAPONS_PLAYABLE: [WeaponData; MAXWEP] = [
    WEAPONS[1],
    WEAPONS[2],
    WEAPONS[3],
    WEAPONS[4],
    WEAPONS[5],
    WEAPONS[6],
    WEAPONS[7],
    WEAPONS[8],
    WEAPONS[9],
    WEAPONS[10],
    WEAPONS[11],
    WEAPONS[12],
    WEAPONS[13],
    WEAPONS[14],
    WEAPONS[15],
    WEAPONS[16],
    WEAPONS[17],
    WEAPONS[18],
    WEAPONS[19],
    WEAPONS[20],
    WEAPONS[21],
    WEAPONS[22],
    WEAPONS[23],
    WEAPONS[24],
    WEAPONS[25],
    WEAPONS[26],
    WEAPONS[27],
    WEAPONS[28],
    WEAPONS[29],
    WEAPONS[30],
    WEAPONS[31],
    WEAPONS[32],
    WEAPONS[33],
    WEAPONS[34],
    WEAPONS[35],
    WEAPONS[36],
    WEAPONS[37],
    WEAPONS[38],
    WEAPONS[39],
    WEAPONS[40],
    WEAPONS[41],
    WEAPONS[42],
    WEAPONS[43],
    WEAPONS[44],
    WEAPONS[45],
    WEAPONS[46],
    WEAPONS[47],
    WEAPONS[48],
    WEAPONS[49],
    WEAPONS[50],
    WEAPONS[51],
    WEAPONS[52],
    WEAPONS[53],
    WEAPONS[54],
    WEAPONS[55],
    WEAPONS[56],
    WEAPONS[57],
    WEAPONS[58],
    WEAPONS[59],
    WEAPONS[60],
    WEAPONS[61],
    WEAPONS[62],
    WEAPONS[63],
    WEAPONS[64],
    WEAPONS[65],
    WEAPONS[66],
    WEAPONS[67],
    WEAPONS[68],
    WEAPONS[69],
    WEAPONS[70],
    WEAPONS[71],
    WEAPONS[72],
    WEAPONS[73],
    WEAPONS[74],
    WEAPONS[75],
    WEAPONS[76],
    WEAPONS[77],
    WEAPONS[78],
    WEAPONS[79],
    WEAPONS[80],
    WEAPONS[81],
    WEAPONS[82],
    WEAPONS[83],
    WEAPONS[84],
    WEAPONS[85],
    WEAPONS[86],
    WEAPONS[87],
    WEAPONS[88],
    WEAPONS[89],
    WEAPONS[90],
    WEAPONS[91],
    WEAPONS[92],
    WEAPONS[93],
    WEAPONS[94],
    WEAPONS[95],
    WEAPONS[96],
    WEAPONS[97],
    WEAPONS[98],
    WEAPONS[99],
    WEAPONS[100],
    WEAPONS[101],
    WEAPONS[102],
    WEAPONS[103],
    WEAPONS[104],
    WEAPONS[105],
    WEAPONS[106],
    WEAPONS[107],
    WEAPONS[108],
    WEAPONS[109],
    WEAPONS[110],
    WEAPONS[111],
    WEAPONS[112],
    WEAPONS[113],
    WEAPONS[114],
    WEAPONS[115],
    WEAPONS[116],
    WEAPONS[117],
    WEAPONS[118],
    WEAPONS[119],
    WEAPONS[120],
    WEAPONS[121],
    WEAPONS[122],
    WEAPONS[123],
    WEAPONS[124],
    WEAPONS[125],
    WEAPONS[126],
    WEAPONS[127],
    WEAPONS[128],
];

pub const fn weapon_by_id(id: usize) -> Option<&'static WeaponData> {
    if id <= MAXWEP {
        Some(&WEAPONS[id])
    } else {
        None
    }
}

pub const fn ammo_max(kind: AmmoType) -> u16 {
    match kind {
        AmmoType::None => 1000,
        AmmoType::Bullets => 255,
        AmmoType::Shells => 55,
        AmmoType::Bolts => 55,
        AmmoType::Explosives => 55,
        AmmoType::Energy => 55,
    }
}

pub const fn ammo_pickup(kind: AmmoType) -> u16 {
    match kind {
        AmmoType::None => 0,
        AmmoType::Bullets => 32,
        AmmoType::Shells => 8,
        AmmoType::Bolts => 7,
        AmmoType::Explosives => 6,
        AmmoType::Energy => 10,
    }
}
